# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateField(auto_now_add=True, verbose_name="زمان درج"),
                ),
            ],
            options={
                "verbose_name": "علاقه مندی",
                "verbose_name_plural": "علاقه مندی ها ",
                "db_table": "c_favorits",
            },
        ),
        migrations.CreateModel(
            name="Scoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateField(auto_now_add=True, verbose_name="زمان درج"),
                ),
                (
                    "score",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز",
                "verbose_name_plural": "امتیازات",
                "db_table": "c_scoring",
            },
        ),
        migrations.CreateModel(
            name="WorkSampleLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                (
                    "register_date",
                    models.DateField(auto_now_add=True, verbose_name="زمان درج"),
                ),
                (
                    "comment_text",
                    models.TextField(blank=True, null=True, verbose_name="متن"),
                ),
                (
                    "approved_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر تایید کننده",
                    ),
                ),
                (
                    "comment_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_user",
                        to="accounts.customer",
                        verbose_name="کاربر نظر دهنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
                "db_table": "c_comments",
            },
        ),
    ]
