# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_initial"),
        ("comments_scores_favories", "0001_initial"),
        ("salons", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_salon",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_services",
                to="services.services",
                verbose_name="خدمات",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_stylist",
                to="accounts.stylist",
                verbose_name=" آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="favorits",
            name="favorite_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_user",
                to="accounts.customer",
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="favorits",
            name="salon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_salon",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="favorits",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_services",
                to="services.services",
                verbose_name="خدمات",
            ),
        ),
        migrations.AddField(
            model_name="favorits",
            name="stylist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_stylist",
                to="accounts.stylist",
                verbose_name=" آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="comment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring",
                to="comments_scores_favories.comments",
                verbose_name="نظر مربوطه",
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="salon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_salon",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="scoring_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_user",
                to="accounts.customer",
                verbose_name="امتیازدهنده",
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_services",
                to="services.services",
                verbose_name="خدمات",
            ),
        ),
        migrations.AddField(
            model_name="scoring",
            name="stylist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_stylist",
                to="accounts.stylist",
                verbose_name=" آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="worksamplelike",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.worksamples"
            ),
        ),
        migrations.AddField(
            model_name="worksamplelike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.customer"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="worksamplelike",
            unique_together={("user", "sample")},
        ),
    ]
