# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentMaterialUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="مقدار مصرف\u200cشده",
                    ),
                ),
                (
                    "unit_cost",
                    models.PositiveIntegerField(
                        default=0, verbose_name="هزینه هر واحد"
                    ),
                ),
                (
                    "total_cost",
                    models.PositiveIntegerField(default=0, verbose_name="هزینه کل"),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("salon", "هزینه با سالن"),
                            ("stylist", "هزینه با آرایشگر"),
                            ("shared", "هزینه مشترک"),
                        ],
                        default="salon",
                        max_length=20,
                        verbose_name="پرداخت\u200cکننده هزینه مواد",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "مواد مصرفی رزرو",
                "verbose_name_plural": "مواد مصرفی رزروها",
                "db_table": "o_appointment_material_usage",
            },
        ),
        migrations.CreateModel(
            name="AppointmentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience_role",
                    models.CharField(
                        choices=[
                            ("customer", "مشتری"),
                            ("stylist", "آرایشگر"),
                            ("manager", "مدیر سالن"),
                            ("system", "سیستم"),
                        ],
                        max_length=20,
                        verbose_name="گروه هدف",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("dashboard", "داشبورد"),
                            ("email", "ایمیل"),
                            ("sms", "پیامک"),
                            ("system", "سیستم"),
                        ],
                        max_length=20,
                        verbose_name="کانال",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("booking_created", "رزرو ثبت شد"),
                            ("booking_paid", "پرداخت رزرو ثبت شد"),
                            ("stylist_confirmed", "تایید آرایشگر"),
                            ("stylist_rejected", "رد رزرو توسط آرایشگر"),
                            ("reminder_scheduled", "یادآوری زمان\u200cبندی شد"),
                            ("reminder_due", "یادآوری نزدیک نوبت"),
                            ("customer_arrived", "مشتری رسید"),
                            ("service_started", "شروع خدمت"),
                            ("service_completed", "پایان خدمت"),
                            ("financial_finalized", "نهایی شدن محاسبات مالی"),
                            ("client_late", "ثبت تاخیر مشتری"),
                            ("client_checked_in_late", "رسیدن مشتری با تاخیر"),
                            ("no_show_pending_review", "عدم حضور در انتظار بررسی"),
                            ("no_show_confirmed", "عدم حضور تایید شده"),
                            ("service_overrun_risk", "ریسک طولانی\u200cشدن خدمت"),
                            ("service_overrun", "طولانی\u200cشدن خدمت"),
                            ("appointment_disputed", "اختلاف نوبت"),
                            ("pay_in_salon_pending", "پرداخت در سالن"),
                            ("payment_completed", "پرداخت تکمیل شد"),
                            ("review_requested", "درخواست نظرسنجی"),
                            ("review_completed", "نظرسنجی ثبت شد"),
                        ],
                        max_length=32,
                        verbose_name="نوع رویداد",
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="عنوان")),
                ("body", models.TextField(blank=True, default="", verbose_name="متن")),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("sent", "ارسال شد"),
                            ("queued", "در صف"),
                            ("pending_setup", "نیازمند تنظیمات"),
                            ("failed", "ناموفق"),
                            ("skipped", "ارسال نشد"),
                        ],
                        default="sent",
                        max_length=20,
                        verbose_name="وضعیت ارسال",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شد"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان خواندن"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
            ],
            options={
                "verbose_name": "اعلان رزرو",
                "verbose_name_plural": "اعلان\u200cهای رزرو",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BookingQuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="توکن لینک",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="عنوان لینک",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("service", "فقط خدمت"),
                            ("stylist", "فقط متخصص"),
                            ("service_stylist", "خدمت + متخصص"),
                            ("service_stylist_time", "خدمت + متخصص + زمان"),
                        ],
                        max_length=32,
                        verbose_name="نوع لینک",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="اطلاعات لینک"
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(
                        default=False,
                        help_text="برای لینک\u200cهایی که در شبکه\u200cهای اجتماعی قرار می\u200cگیرند فعال شود.",
                        verbose_name="لینک دائمی",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "bookings_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد رزرو ثبت\u200cشده"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان مصرف لینک"
                    ),
                ),
                (
                    "disabled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان غیرفعال\u200cسازی"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انقضا"
                    ),
                ),
                (
                    "last_opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین بازدید"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
            ],
            options={
                "verbose_name": "لینک سریع رزرو",
                "verbose_name_plural": "لینک\u200cهای سریع رزرو",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DelayPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grace_period_minutes",
                    models.PositiveIntegerField(
                        default=10, verbose_name="مهلت قابل قبول تاخیر مشتری"
                    ),
                ),
                (
                    "no_show_after_minutes",
                    models.PositiveIntegerField(
                        default=20, verbose_name="ثبت عدم حضور بعد از چند دقیقه"
                    ),
                ),
                (
                    "no_show_dispute_window_hours",
                    models.PositiveIntegerField(
                        default=12, verbose_name="مهلت بررسی/اعتراض عدم حضور"
                    ),
                ),
                (
                    "default_service_buffer_minutes",
                    models.PositiveIntegerField(
                        default=10, verbose_name="بافر پیش\u200cفرض خدمات"
                    ),
                ),
                (
                    "customer_facing_text",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="متن قابل نمایش قوانین تاخیر به مشتری",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "قانون تاخیر سالن",
                "verbose_name_plural": "قوانین تاخیر سالن\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تایید"),
                            ("confirmed", "تایید شده"),
                            ("paid", "پرداخت شده"),
                            ("completed", "انجام شده"),
                            ("cancelled", "لغو شده"),
                            ("no_show", "عدم حضور"),
                            ("disputed", "دارای اختلاف"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "register_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "update_date",
                    models.DateField(auto_now=True, verbose_name="تاریخ آپدیت"),
                ),
                (
                    "is_finally",
                    models.BooleanField(default=False, verbose_name="نهایی شده"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="پرداخت شده"),
                ),
                (
                    "order_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="کد سفارش",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="تخفیف"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "stylist_approved",
                    models.BooleanField(default=False, verbose_name="تایید آرایشگر"),
                ),
                (
                    "selected_payment_method",
                    models.CharField(
                        choices=[
                            ("online", "پرداخت آنلاین"),
                            ("wallet", "کیف پول"),
                            ("pay_in_salon", "پرداخت در سالن"),
                        ],
                        default="pay_in_salon",
                        max_length=20,
                        verbose_name="روش پرداخت انتخابی",
                    ),
                ),
                (
                    "requires_online_payment",
                    models.BooleanField(
                        default=False, verbose_name="الزام پرداخت آنلاین"
                    ),
                ),
                (
                    "subtotal_amount",
                    models.PositiveIntegerField(default=0, verbose_name="جمع خدمات"),
                ),
                (
                    "discount_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مبلغ تخفیف"),
                ),
                (
                    "basket_discount_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ تخفیف خدمات"
                    ),
                ),
                (
                    "coupon_discount_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ تخفیف کد"
                    ),
                ),
                (
                    "basket_discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="درصد تخفیف خدمات"
                    ),
                ),
                (
                    "basket_discount_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="عنوان سبد تخفیف",
                    ),
                ),
                (
                    "tax_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مالیات"),
                ),
                (
                    "total_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مبلغ نهایی"),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="کد تخفیف اعمال شده",
                    ),
                ),
                (
                    "discount_rules_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="اسنپ\u200cشات قوانین تخفیف",
                    ),
                ),
                (
                    "platform_commission_applies",
                    models.BooleanField(
                        default=False, verbose_name="مشمول کارمزد اولین مراجعه"
                    ),
                ),
                (
                    "platform_commission_percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="درصد کارمزد پلتفرم"
                    ),
                ),
                (
                    "platform_commission_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ کارمزد پلتفرم"
                    ),
                ),
                (
                    "salon_payout_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ تسویه به سالن"
                    ),
                ),
                (
                    "checkout_locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان قفل شدن چک\u200cاوت"
                    ),
                ),
                (
                    "refunded_to_wallet_amount",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="مبلغ بازگشت\u200cداده\u200cشده به کیف پول",
                    ),
                ),
                (
                    "refunded_to_wallet_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بازگشت وجه به کیف پول"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="دلیل لغو"
                    ),
                ),
                (
                    "booking_source",
                    models.CharField(
                        choices=[
                            ("customer", "رزرو کاربر"),
                            ("dashboard_manual", "رزرو دستی داشبورد"),
                        ],
                        default="customer",
                        max_length=32,
                        verbose_name="منبع ثبت رزرو",
                    ),
                ),
                (
                    "stylist_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تایید آرایشگر"
                    ),
                ),
                (
                    "customer_arrived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان رسیدن مشتری"
                    ),
                ),
                (
                    "service_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان شروع خدمت"
                    ),
                ),
                (
                    "service_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پایان خدمت"
                    ),
                ),
                (
                    "reminder_due_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="زمان برنامه\u200cریزی یادآوری",
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال یادآوری"
                    ),
                ),
                (
                    "reminder_status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار ارسال"),
                            ("scheduled", "زمان\u200cبندی شد"),
                            ("sent", "ارسال شد"),
                            ("skipped", "رد شد"),
                            ("cancelled", "لغو شد"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت یادآوری",
                    ),
                ),
                (
                    "review_requested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان درخواست نظرسنجی"
                    ),
                ),
                (
                    "review_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ثبت نظرسنجی"
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش ها",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name=" قیمت")),
                ("date", models.DateField(null=True, verbose_name="تاریخ")),
                ("time", models.TimeField(null=True, verbose_name="زمان")),
                ("end_time", models.TimeField(null=True, verbose_name="زمان پایان")),
                (
                    "scheduled_duration_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="در زمان رزرو از مدت خدمت snapshot می\u200cشود تا تغییرات بعدی روی نوبت\u200cهای قبلی اثر نگذارد.",
                        verbose_name="مدت زمان زمان\u200cبندی\u200cشده خدمت",
                    ),
                ),
                (
                    "buffer_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="این زمان بعد از پایان خدمت برای جلوگیری از تداخل نوبت بعدی لحاظ می\u200cشود.",
                        verbose_name="بافر رزروشده بعد از خدمت",
                    ),
                ),
                (
                    "occupied_until",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="پایان اشغال تقویم با احتساب بافر",
                    ),
                ),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تایید"),
                            ("confirmed", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت تایید آرایشگر",
                    ),
                ),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("awaiting_confirmation", "در انتظار تایید"),
                            ("confirmed", "تایید شده"),
                            ("client_late", "مشتری با تاخیر"),
                            ("no_show_pending_review", "عدم حضور در انتظار بررسی"),
                            ("no_show_confirmed", "عدم حضور تایید شده"),
                            ("arrived", "مشتری رسید"),
                            ("in_service", "در حال انجام"),
                            ("service_overrun", "طولانی\u200cشدن خدمت"),
                            ("completed", "تکمیل شده"),
                            ("disputed", "دارای اختلاف"),
                        ],
                        default="awaiting_confirmation",
                        max_length=32,
                        verbose_name="وضعیت اجرای خدمت",
                    ),
                ),
                (
                    "stylist_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="زمان تایید این خدمت توسط آرایشگر",
                    ),
                ),
                (
                    "stylist_rejected_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="زمان رد این خدمت توسط آرایشگر",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="دلیل رد خدمت",
                    ),
                ),
                (
                    "customer_arrived_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="زمان رسیدن مشتری برای این خدمت",
                    ),
                ),
                (
                    "service_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان شروع این خدمت"
                    ),
                ),
                (
                    "service_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پایان این خدمت"
                    ),
                ),
                (
                    "financial_finalized_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="زمان نهایی شدن مالی این خدمت",
                    ),
                ),
                (
                    "client_late_recorded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ثبت تاخیر مشتری"
                    ),
                ),
                (
                    "client_late_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="میزان تاخیر مشتری به دقیقه"
                    ),
                ),
                (
                    "no_show_pending_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="زمان ثبت عدم حضور در انتظار بررسی",
                    ),
                ),
                (
                    "no_show_dispute_until",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="مهلت اعتراض یا بررسی عدم حضور",
                    ),
                ),
                (
                    "no_show_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تایید نهایی عدم حضور"
                    ),
                ),
                (
                    "expected_service_completed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="زمان مورد انتظار پایان خدمت",
                    ),
                ),
                (
                    "service_overrun_recorded_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="زمان ثبت طولانی\u200cشدن خدمت",
                    ),
                ),
                (
                    "service_overrun_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="میزان طولانی\u200cشدن خدمت به دقیقه"
                    ),
                ),
                (
                    "service_overrun_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="دلیل طولانی\u200cشدن خدمت",
                    ),
                ),
                (
                    "disputed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ورود به وضعیت اختلاف"
                    ),
                ),
                (
                    "operational_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت عملیاتی"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_title",
                    models.CharField(max_length=50, verbose_name="نوع پرداخت"),
                ),
            ],
            options={
                "verbose_name": "نوع پرداخت",
                "verbose_name_plural": "انواغ روش پرداخت",
            },
        ),
        migrations.CreateModel(
            name="AppointmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "ثبت رزرو"),
                            ("stylist_confirmed", "تایید آرایشگر"),
                            ("stylist_rejected", "رد آرایشگر"),
                            ("client_late", "ثبت تاخیر مشتری"),
                            ("customer_arrived", "رسیدن مشتری"),
                            ("service_started", "شروع خدمت"),
                            ("service_overrun", "طولانی\u200cشدن خدمت"),
                            ("service_completed", "پایان خدمت"),
                            ("no_show_pending", "عدم حضور در انتظار بررسی"),
                            ("no_show_confirmed", "عدم حضور تایید شده"),
                            ("disputed", "اختلاف"),
                            ("status_changed", "تغییر وضعیت"),
                            ("note", "یادداشت"),
                        ],
                        max_length=64,
                        verbose_name="نوع رویداد",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="وضعیت قبلی"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="وضعیت جدید"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد نوبت",
                "verbose_name_plural": "رویدادهای نوبت",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
