# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_initial"),
        ("orders", "0001_initial"),
        ("salons", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentevent",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_events",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="appointmentevent",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_events",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="appointmentmaterialusage",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment_usages",
                to="services.materialitem",
                verbose_name="ماده مصرفی",
            ),
        ),
        migrations.AddField(
            model_name="appointmentmaterialusage",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_material_usages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="appointmentmaterialusage",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_usages",
                to="services.servicematerialtemplate",
                verbose_name="قالب اولیه مواد",
            ),
        ),
        migrations.AddField(
            model_name="appointmentnotification",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_notifications",
                to="accounts.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="appointmentnotification",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_notifications",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="appointmentnotification",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_notifications",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="appointmentnotification",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر هدف",
            ),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_quick_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سازنده لینک",
            ),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_quick_links",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_quick_links",
                to="services.services",
                verbose_name="خدمت",
            ),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_quick_links",
                to="accounts.stylist",
                verbose_name="متخصص",
            ),
        ),
        migrations.AddField(
            model_name="delaypolicy",
            name="salon",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delay_policy",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="used_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_quick_links",
                to="orders.order",
                verbose_name="رزرو مصرف\u200cکننده لینک",
            ),
        ),
        migrations.AddField(
            model_name="appointmentnotification",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AddField(
            model_name="appointmentevent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_events",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="no_show_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_no_show_order_details",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تاییدکننده عدم حضور",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_details1",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_details_salon",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_details_services",
                to="services.services",
                verbose_name="خدمت",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="stylist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_details_stylist",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="appointmentnotification",
            name="order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="orders.orderdetail",
                verbose_name="آیتم رزرو",
            ),
        ),
        migrations.AddField(
            model_name="appointmentmaterialusage",
            name="order_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_usages",
                to="orders.orderdetail",
                verbose_name="آیتم رزرو",
            ),
        ),
        migrations.AddField(
            model_name="appointmentevent",
            name="order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="orders.orderdetail",
                verbose_name="آیتم رزرو",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="orders.paymenttype",
                verbose_name="نوع پرداخت",
            ),
        ),
        migrations.AddIndex(
            model_name="orderdetail",
            index=models.Index(
                fields=["salon", "date", "time"], name="orderdetail_salon_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdetail",
            index=models.Index(
                fields=["stylist", "date", "time"], name="orderdetail_stylist_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdetail",
            index=models.Index(
                fields=["lifecycle_status", "date"], name="orderdetail_lifecycle_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdetail",
            index=models.Index(
                fields=["no_show_pending_at"], name="orddet_no_show_pend_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentmaterialusage",
            index=models.Index(
                fields=["order_detail", "material"], name="appt_mat_usage_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentmaterialusage",
            index=models.Index(fields=["paid_by"], name="appt_mat_paid_by_idx"),
        ),
        migrations.AddConstraint(
            model_name="appointmentmaterialusage",
            constraint=models.UniqueConstraint(
                fields=("order_detail", "material"), name="uniq_mat_usage_orderdet"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentmaterialusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="appt_mat_qty_gte0"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentmaterialusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="appt_mat_unit_cost_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentmaterialusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_cost__gte", 0)), name="appt_mat_total_gte0"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentevent",
            index=models.Index(
                fields=["order", "created_at"], name="appt_event_order_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentevent",
            index=models.Index(
                fields=["order_detail", "created_at"], name="appt_event_detail_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="appt_event_type_time_idx"
            ),
        ),
    ]
