# Generated by Django 5.1.4 on 2026-07-22 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingquicklink",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="زمان بایگانی"
            ),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="campaign_name",
            field=models.CharField(
                blank=True, default="", max_length=160, verbose_name="نام کمپین"
            ),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="internal_note",
            field=models.TextField(
                blank=True, default="", verbose_name="یادداشت داخلی"
            ),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="last_converted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="آخرین رزرو موفق"
            ),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="opens_count",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد بازشدن"),
        ),
        migrations.AddField(
            model_name="bookingquicklink",
            name="placement",
            field=models.CharField(
                choices=[
                    ("direct", "ارسال مستقیم به مشتری"),
                    ("mirror_label", "لیبل کنار آینه"),
                    ("reception", "پذیرش"),
                    ("table_stand", "استند رومیزی"),
                    ("booking_card", "کارت رزرو"),
                    ("instagram_bio", "بیوی اینستاگرام"),
                    ("instagram_story", "استوری اینستاگرام"),
                    ("whatsapp", "واتساپ"),
                    ("other", "سایر"),
                ],
                db_index=True,
                default="other",
                max_length=32,
                verbose_name="محل استفاده",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="booking_quick_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributed_orders",
                to="orders.bookingquicklink",
                verbose_name="لینک رزرو منتسب",
            ),
        ),
    ]
