# Generated by Django 5.1.4 on 2026-07-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_booking_quick_link_management_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingquicklink",
            name="mode",
            field=models.CharField(
                choices=[
                    ("salon", "صفحه اصلی سالن"),
                    ("service", "فقط خدمت"),
                    ("stylist", "فقط متخصص"),
                    ("service_stylist", "خدمت + متخصص"),
                    ("service_stylist_time", "خدمت + متخصص + زمان"),
                ],
                max_length=32,
                verbose_name="نوع لینک",
            ),
        ),
    ]
