# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("salons", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(max_length=255, verbose_name="شماره تماس اضطراری"),
                ),
                (
                    "relationship",
                    models.CharField(max_length=255, verbose_name="نسبت با آرایشگر"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="نام و نام خانوادگی  ",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_info",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات اضطراری",
                "verbose_name_plural": "اطلاعات اضطراری",
            },
        ),
        migrations.CreateModel(
            name="JobDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاریخ شروع"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="نوع استخدام",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_job_details",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_details",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "جزئیات شغلی",
                "verbose_name_plural": "جزئیات شغلی",
            },
        ),
        migrations.CreateModel(
            name="StylistSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ ")),
                ("start_time", models.TimeField(verbose_name="زمان شروع")),
                ("end_time", models.TimeField(verbose_name="زمان پایان")),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_schedules",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_schedules",
                        to="services.services",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stylist_schedules",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه آرایشگر",
                "verbose_name_plural": "برنامه\u200cهای آرایشگران",
                "unique_together": {("stylist", "date", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="ProfessionalResumeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, default="", verbose_name="پیام آرایشگر"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "ارسال شده"),
                            ("viewed", "مشاهده شده"),
                            ("invited", "دعوت به همکاری"),
                            ("rejected", "رد شده"),
                            ("saved", "ذخیره شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "resume_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="اسنپ\u200cشات رزومه"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان مشاهده"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پاسخ"
                    ),
                ),
                (
                    "response_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت پاسخ سالن"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ارسال"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_resume_submissions",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_submissions",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارسال رزومه آرایشگر",
                "verbose_name_plural": "ارسال\u200cهای رزومه آرایشگران",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["stylist", "status"], name="resume_sub_sty_stat_idx"
                    ),
                    models.Index(
                        fields=["salon", "status"], name="resume_sub_sal_stat_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ مرخصی")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="ساعت شروع"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="ساعت پایان"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="دلیل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت بررسی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_staff_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بررسی\u200cکننده",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_leave_requests",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست مرخصی آرایشگر",
                "verbose_name_plural": "درخواست\u200cهای مرخصی آرایشگران",
                "indexes": [
                    models.Index(
                        fields=["salon", "stylist", "status"],
                        name="staff_leave_lookup_idx",
                    ),
                    models.Index(
                        fields=["stylist", "date"], name="staff_leave_date_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffScheduleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ برنامه")),
                ("start_time", models.TimeField(verbose_name="ساعت شروع")),
                ("end_time", models.TimeField(verbose_name="ساعت پایان")),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", verbose_name="توضیح متخصص"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت مدیر"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_staff_schedule_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بررسی\u200cکننده",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_schedule_requests",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_requests",
                        to="services.services",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_requests",
                        to="accounts.stylist",
                        verbose_name="متخصص",
                    ),
                ),
                (
                    "created_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_requests",
                        to="stylists.stylistschedule",
                        verbose_name="برنامه ساخته\u200cشده",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست برنامه کاری متخصص",
                "verbose_name_plural": "درخواست\u200cهای برنامه کاری متخصصان",
                "indexes": [
                    models.Index(
                        fields=["salon", "stylist", "status"],
                        name="staff_sched_req_lookup_idx",
                    ),
                    models.Index(
                        fields=["stylist", "date"], name="staff_sched_req_date_idx"
                    ),
                    models.Index(
                        fields=["salon", "status", "date"],
                        name="staff_sched_req_queue_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StylistTimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ تعطیلی")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="زمان شروع تعطیلی"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="زمان پایان تعطیلی"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="دلیل"
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_offs",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعطیلی آرایشگر",
                "verbose_name_plural": "تعطیلی\u200cهای آرایشگر",
                "unique_together": {("stylist", "date", "start_time")},
            },
        ),
    ]
