# Generated by Django 5.1.4 on 2026-08-31 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('salons', '0004_salon_onboarding_contact_address_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccountConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_account_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('account_type', models.CharField(blank=True, default='', max_length=32)),
                ('encrypted_access_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('needs_reauth', 'Needs re-authentication'), ('disconnected', 'Disconnected')], db_index=True, default='disconnected', max_length=32)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_connections', to='salons.salon')),
                ('stylist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_connections', to='accounts.stylist')),
            ],
            options={
                'db_table': 'instagram_account_connections',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['salon', 'status'], name='ig_conn_salon_status'), models.Index(fields=['stylist', 'status'], name='ig_conn_sty_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('stylist__isnull', True)), fields=('salon',), name='uniq_instagram_salon_context'), models.UniqueConstraint(condition=models.Q(('stylist__isnull', False)), fields=('salon', 'stylist'), name='uniq_instagram_stylist_context')],
            },
        ),
    ]
