# Generated by Django 5.1.4 on 2026-08-31 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sender_igsid', models.CharField(db_index=True, max_length=128)),
                ('recipient_instagram_account_id', models.CharField(db_index=True, max_length=64)),
                ('message_text', models.TextField(blank=True, default='')),
                ('provider_timestamp_ms', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='received', max_length=32)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='instagram_integration.instagramaccountconnection')),
            ],
            options={
                'db_table': 'instagram_inbound_messages',
                'ordering': ['received_at', 'id'],
                'indexes': [models.Index(fields=['connection', 'status'], name='ig_msg_conn_status'), models.Index(fields=['sender_igsid', 'received_at'], name='ig_msg_sender_time')],
            },
        ),
    ]
