# Generated by Django 5.1.4 on 2026-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_integration', '0002_instagraminboundmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagraminboundmessage',
            name='lumi_disposition',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='instagraminboundmessage',
            name='lumi_facts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instagraminboundmessage',
            name='lumi_reply_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instagraminboundmessage',
            name='requires_human',
            field=models.BooleanField(default=False),
        ),
    ]
