# Generated by Django 5.1.4 on 2026-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_integration', '0003_instagraminboundmessage_lumi_disposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagraminboundmessage',
            name='reply_last_error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='instagraminboundmessage',
            name='reply_provider_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='instagraminboundmessage',
            name='reply_send_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagraminboundmessage',
            name='reply_send_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='instagraminboundmessage',
            name='reply_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
