# Generated by Django 5.1.4 on 2026-08-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_integration', '0004_instagraminboundmessage_reply_last_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccountconnection',
            name='webhook_subscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
