# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
import django.utils.timezone
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره موبایل"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=100, verbose_name="ایمیل"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, verbose_name="نام"),
                ),
                (
                    "family",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نام خانوادگی"
                    ),
                ),
                (
                    "register_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="وضعیت "),
                ),
                (
                    "active_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="کد فعال سازی",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.A user will get all permissions granted to each of their groups.",
                        related_name="custom_user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "db_table": "A_CustomUser",
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="آدرس", max_length=60, verbose_name="عنوان آدرس"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="نام گیرنده"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="شهر"),
                ),
                ("address_line", models.TextField(verbose_name="متن آدرس")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="کد پستی"),
                ),
                (
                    "plaque",
                    models.CharField(blank=True, max_length=20, verbose_name="پلاک"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=20, verbose_name="واحد"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="آدرس پیش\u200cفرض"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "آدرس مشتری",
                "verbose_name_plural": "آدرس\u200cهای مشتری",
                "db_table": "A_CustomerAddresses",
                "ordering": ["-is_default", "-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkSamples",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_image",
                    models.ImageField(
                        upload_to=utils.File_Uploader("images", "work_samples"),
                        verbose_name="تصویر نمونه کار",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد لایک"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="نمایش عمومی"),
                ),
                (
                    "is_verified_work",
                    models.BooleanField(
                        default=False, verbose_name="نمونه\u200cکار تأییدشده"
                    ),
                ),
                (
                    "contains_identifiable_client",
                    models.BooleanField(
                        default=False, verbose_name="دارای هویت قابل تشخیص مشتری"
                    ),
                ),
                (
                    "client_consent_status",
                    models.CharField(
                        default="not_required",
                        max_length=64,
                        verbose_name="وضعیت رضایت مشتری",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        db_index=True,
                        default="published",
                        max_length=64,
                        verbose_name="وضعیت بررسی",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمونه کار",
                "verbose_name_plural": "نمونه کار ها",
                "db_table": "A_Work_Samples",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="customer_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader("images", "customers"),
                        verbose_name="تصویر مشتری",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "مرد"), ("female", "زن"), ("other", "سایر")],
                        max_length=10,
                        null=True,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "notify_appointment_sms",
                    models.BooleanField(
                        default=True,
                        verbose_name="اطلاع رسانی قرار ملاقات از طریق پیامک",
                    ),
                ),
                (
                    "notify_appointment_whatsapp",
                    models.BooleanField(
                        default=True,
                        verbose_name="اطلاع رسانی قرار ملاقات از طریق واتس اپ",
                    ),
                ),
                (
                    "notify_appointment_email",
                    models.BooleanField(
                        default=True,
                        verbose_name="اطلاع رسانی قرار ملاقات از طریق ایمیل",
                    ),
                ),
                (
                    "notify_marketing_email",
                    models.BooleanField(
                        default=True, verbose_name="اطلاع رسانی بازاریابی از طریق ایمیل"
                    ),
                ),
                (
                    "notify_marketing_sms",
                    models.BooleanField(
                        default=True, verbose_name="اطلاع رسانی بازاریابی از طریق پیامک"
                    ),
                ),
                (
                    "notify_marketing_whatsapp",
                    models.BooleanField(
                        default=True,
                        verbose_name="اطلاع رسانی بازاریابی از طریق واتس اپ",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتری ها ",
                "db_table": "A_Customers",
            },
        ),
        migrations.CreateModel(
            name="SalonManager",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="salon_manager_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader("images", "salon_manager"),
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "salon_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تلفن سالن"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                ("slug", models.SlugField(blank=True, null=True, verbose_name="اسلاگ")),
            ],
            options={
                "verbose_name": "مدیر سالن",
                "verbose_name_plural": "مدیران سالن ها",
                "db_table": "A_Salon_Managers",
            },
        ),
        migrations.CreateModel(
            name="Stylist",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "linkedin_link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="لینک لینکدین",
                    ),
                ),
                (
                    "insta_link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="لینک اینستا",
                    ),
                ),
                (
                    "telegram_link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="لینک تلگرام ",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader("images", "stylists"),
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                (
                    "expert",
                    models.CharField(max_length=100, null=True, verbose_name="تخصص"),
                ),
                (
                    "calendar_color",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="رنگ تقویم "
                    ),
                ),
                (
                    "notify_booking_dashboard",
                    models.BooleanField(
                        default=True, verbose_name="اعلان رزرو در داشبورد آرایشگر"
                    ),
                ),
                (
                    "notify_booking_email",
                    models.BooleanField(
                        default=True, verbose_name="اعلان رزرو با ایمیل برای آرایشگر"
                    ),
                ),
                (
                    "notify_booking_sms",
                    models.BooleanField(
                        default=False, verbose_name="اعلان رزرو با پیامک برای آرایشگر"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="نام نمایشی حرفه\u200cای",
                    ),
                ),
                (
                    "started_working_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="سال شروع فعالیت"
                    ),
                ),
                (
                    "public_visibility",
                    models.CharField(
                        choices=[
                            ("hidden", "مخفی"),
                            ("salon_only", "فقط در سالن\u200cهای فعال"),
                            ("public", "عمومی در Loomera"),
                            ("resume_only", "فقط رزومه قابل ارسال"),
                        ],
                        db_index=True,
                        default="salon_only",
                        max_length=32,
                        verbose_name="وضعیت نمایش پروفایل",
                    ),
                ),
                (
                    "is_verified_professional",
                    models.BooleanField(default=False, verbose_name="متخصص تأییدشده"),
                ),
                (
                    "profile_locked_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت سیستمی رزومه"
                    ),
                ),
                (
                    "resume_headline",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=180,
                        verbose_name="تیتر رزومه حرفه\u200cای",
                    ),
                ),
                (
                    "resume_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="خلاصه رزومه حرفه\u200cای"
                    ),
                ),
            ],
            options={
                "verbose_name": "آرایشگر",
                "verbose_name_plural": "آرایشگران",
                "db_table": "a_stylists",
            },
        ),
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_user_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="شناسه کاربر اصلی",
                    ),
                ),
                (
                    "original_mobile_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="موبایل اصلی",
                    ),
                ),
                (
                    "original_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="ایمیل اصلی",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="دلیل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "درخواست شده"),
                            ("anonymized", "ناشناس\u200cسازی شده"),
                            ("completed", "تکمیل شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="requested",
                        max_length=32,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ درخواست"
                    ),
                ),
                (
                    "anonymized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ ناشناس\u200cسازی"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تکمیل"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست حذف حساب",
                "verbose_name_plural": "درخواست\u200cهای حذف حساب",
                "db_table": "A_AccountDeletionRequests",
                "ordering": ["-requested_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("booking", "رزرو"),
                            ("payment", "پرداخت"),
                            ("wallet", "کیف پول"),
                            ("support", "پشتیبانی"),
                            ("system", "سیستمی"),
                            ("marketing", "پیشنهادها"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=24,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "کم"), ("normal", "معمولی"), ("high", "مهم")],
                        default="normal",
                        max_length=12,
                        verbose_name="اولویت",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="عنوان")),
                ("body", models.TextField(blank=True, verbose_name="متن اعلان")),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="می\u200cتواند یک مسیر داخلی مثل /orders/appointments/ باشد.",
                        max_length=500,
                        verbose_name="لینک اقدام",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="fa-regular fa-bell",
                        max_length=80,
                        verbose_name="کلاس آیکون",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="خوانده شده"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ خواندن"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان مشتری",
                "verbose_name_plural": "اعلان\u200cهای مشتری",
                "db_table": "A_CustomerNotifications",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("terms", "پذیرش قوانین استفاده"),
                            ("privacy", "پذیرش سیاست حریم خصوصی"),
                            ("marketing", "اجازه پیام\u200cهای بازاریابی"),
                            ("image_publication", "اجازه انتشار تصویر"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="نوع رضایت",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=32, verbose_name="نسخه متن"
                    ),
                ),
                (
                    "is_granted",
                    models.BooleanField(default=True, verbose_name="تأیید شده"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="منبع"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "رضایت کاربر",
                "verbose_name_plural": "رضایت\u200cهای کاربران",
                "db_table": "A_UserConsents",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
