# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("salons", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksamples",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_samples",
                to="salons.salon",
                verbose_name="سالن مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="worksamples",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_samples_services",
                to="services.services",
                verbose_name="خدمت ",
            ),
        ),
        migrations.AddField(
            model_name="customernotification",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="accounts.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="added_by_salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_customers",
                to="salons.salon",
                verbose_name="اضافه شده توسط سالن",
            ),
        ),
        migrations.AddField(
            model_name="worksamples",
            name="stylist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_samples_of_stylist",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddIndex(
            model_name="accountdeletionrequest",
            index=models.Index(
                fields=["status", "-requested_at"], name="A_AccountDe_status_066790_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountdeletionrequest",
            index=models.Index(
                fields=["original_user_id"], name="A_AccountDe_origina_cba54d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userconsent",
            index=models.Index(
                fields=["user", "consent_type", "-created_at"],
                name="A_UserConse_user_id_56516a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userconsent",
            index=models.Index(
                fields=["consent_type", "is_granted", "-created_at"],
                name="A_UserConse_consent_f5343f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customernotification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="A_CustomerN_user_id_2fce51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customernotification",
            index=models.Index(
                fields=["customer", "category", "-created_at"],
                name="A_CustomerN_custome_fd3cd2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customernotification",
            index=models.Index(
                fields=["category", "-created_at"],
                name="A_CustomerN_categor_c2a472_idx",
            ),
        ),
    ]
