# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagingProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("bale", "بله"),
                            ("telegram", "تلگرام"),
                            ("whatsapp", "واتس\u200cاپ"),
                            ("rubika", "روبیکا"),
                        ],
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="کلید provider",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="عنوان")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="فعال"
                    ),
                ),
                (
                    "supports_webhook",
                    models.BooleanField(default=True, verbose_name="پشتیبانی webhook"),
                ),
                (
                    "supports_callback",
                    models.BooleanField(default=True, verbose_name="پشتیبانی callback"),
                ),
                (
                    "supports_outbound",
                    models.BooleanField(
                        default=True, verbose_name="پشتیبانی ارسال پیام"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
            ],
            options={
                "verbose_name": "provider پیام\u200cرسان",
                "verbose_name_plural": "providerهای پیام\u200cرسان",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="MessagingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("connect_account", "اتصال حساب"),
                            ("disconnect_account", "قطع اتصال حساب"),
                            ("action", "اکشن عملیاتی"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="کاربرد",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="هش توکن",
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        db_index=True, max_length=12, verbose_name="پیشوند توکن"
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه آبجکت مرتبط"
                    ),
                ),
                (
                    "action_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="کلید اکشن",
                    ),
                ),
                (
                    "audience_role",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=24,
                        verbose_name="نقش مخاطب",
                    ),
                ),
                (
                    "salon_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="شناسه سالن scope",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="زمان انقضا"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="زمان استفاده",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="زمان لغو"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name": "توکن پیام\u200cرسان",
                "verbose_name_plural": "توکن\u200cهای پیام\u200cرسان",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MessagingWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=160,
                        verbose_name="event_id",
                    ),
                ),
                (
                    "update_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=160,
                        verbose_name="update_id",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=80,
                        verbose_name="نوع event",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="payload خام"
                    ),
                ),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="headers"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "دریافت\u200cشده"),
                            ("duplicate", "تکراری"),
                            ("ignored", "نادیده\u200cگرفته\u200cشده"),
                            ("processed", "پردازش\u200cشده"),
                            ("failed", "ناموفق"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="خطا"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان دریافت"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پردازش"
                    ),
                ),
            ],
            options={
                "verbose_name": "event وبهوک پیام\u200cرسان",
                "verbose_name_plural": "eventهای وبهوک پیام\u200cرسان",
                "ordering": ["-received_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MessagingIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        verbose_name="شناسه کاربر در provider",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=128,
                        verbose_name="chat_id",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=20,
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="نام کاربری",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="نام نمایشی",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="زبان"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("guest", "مهمان"),
                            ("linked", "متصل به حساب"),
                            ("disconnected", "قطع اتصال"),
                            ("blocked", "مسدود"),
                        ],
                        db_index=True,
                        default="guest",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "raw_profile",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پروفایل خام"
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="اولین مشاهده"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="آخرین مشاهده",
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان اتصال"
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان قطع اتصال"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messaging_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر متصل",
                    ),
                ),
            ],
            options={
                "verbose_name": "هویت پیام\u200cرسان",
                "verbose_name_plural": "هویت\u200cهای پیام\u200cرسان",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MessagingActionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_key",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="کلید اکشن"
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه آبجکت مرتبط"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "شروع\u200cشده"),
                            ("succeeded", "موفق"),
                            ("failed", "ناموفق"),
                            ("denied", "غیرمجاز"),
                            ("expired", "منقضی"),
                            ("already_used", "قبلاً استفاده\u200cشده"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, default=dict, verbose_name="نتیجه"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پایان"
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="نوع آبجکت مرتبط",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messaging_action_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_executions",
                        to="messaging.messagingidentity",
                        verbose_name="هویت پیام\u200cرسان",
                    ),
                ),
            ],
            options={
                "verbose_name": "اجرای اکشن پیام\u200cرسان",
                "verbose_name_plural": "اجرای اکشن\u200cهای پیام\u200cرسان",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MessagingAccountConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("disconnected", "قطع\u200cشده"),
                            ("revoked", "لغوشده"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="زمان اتصال",
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان قطع اتصال"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messaging_account_connections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_connections",
                        to="messaging.messagingidentity",
                        verbose_name="هویت پیام\u200cرسان",
                    ),
                ),
            ],
            options={
                "verbose_name": "اتصال حساب پیام\u200cرسان",
                "verbose_name_plural": "اتصال\u200cهای حساب پیام\u200cرسان",
                "ordering": ["-connected_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MessagingMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "ورودی"), ("outbound", "خروجی")],
                        db_index=True,
                        max_length=16,
                        verbose_name="جهت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "دریافت\u200cشده"),
                            ("queued", "در صف"),
                            ("sent", "ارسال\u200cشده"),
                            ("failed", "ناموفق"),
                            ("skipped", "ارسال\u200cنشده"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "external_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=160,
                        verbose_name="شناسه پیام provider",
                    ),
                ),
                ("text", models.TextField(blank=True, default="", verbose_name="متن")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="payload"),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ provider"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان دریافت"
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_logs",
                        to="messaging.messagingidentity",
                        verbose_name="هویت پیام\u200cرسان",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ پیام پیام\u200cرسان",
                "verbose_name_plural": "لاگ پیام\u200cهای پیام\u200cرسان",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
