# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("messaging", "0001_initial"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messagingmessagelog",
            name="notification_delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messaging_message_logs",
                to="notifications.notificationdelivery",
                verbose_name="ارسال اعلان",
            ),
        ),
        migrations.AddField(
            model_name="messagingmessagelog",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="message_logs",
                to="messaging.messagingprovider",
                verbose_name="provider",
            ),
        ),
        migrations.AddField(
            model_name="messagingidentity",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identities",
                to="messaging.messagingprovider",
                verbose_name="provider",
            ),
        ),
        migrations.AddField(
            model_name="messagingactionexecution",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="action_executions",
                to="messaging.messagingprovider",
                verbose_name="provider",
            ),
        ),
        migrations.AddField(
            model_name="messagingaccountconnection",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="account_connections",
                to="messaging.messagingprovider",
                verbose_name="provider",
            ),
        ),
        migrations.AddField(
            model_name="messagingtoken",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="messaging.messagingidentity",
                verbose_name="هویت پیام\u200cرسان",
            ),
        ),
        migrations.AddField(
            model_name="messagingtoken",
            name="notification_delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messaging_tokens",
                to="notifications.notificationdelivery",
                verbose_name="ارسال اعلان",
            ),
        ),
        migrations.AddField(
            model_name="messagingtoken",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tokens",
                to="messaging.messagingprovider",
                verbose_name="provider",
            ),
        ),
        migrations.AddField(
            model_name="messagingtoken",
            name="related_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="نوع آبجکت مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="messagingtoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messaging_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="messagingactionexecution",
            name="token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_execution",
                to="messaging.messagingtoken",
                verbose_name="توکن",
            ),
        ),
        migrations.AddField(
            model_name="messagingwebhookevent",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="messaging.messagingidentity",
                verbose_name="هویت پیام\u200cرسان",
            ),
        ),
        migrations.AddField(
            model_name="messagingwebhookevent",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="webhook_events",
                to="messaging.messagingprovider",
                verbose_name="provider",
            ),
        ),
        migrations.AddIndex(
            model_name="messagingmessagelog",
            index=models.Index(
                fields=["provider", "direction", "status", "created_at"],
                name="msg_log_provider_dir_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagingmessagelog",
            index=models.Index(
                fields=["identity", "created_at"], name="msg_log_identity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagingmessagelog",
            index=models.Index(
                fields=["notification_delivery", "created_at"],
                name="msg_log_delivery_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagingidentity",
            index=models.Index(
                fields=["provider", "status"], name="msg_ident_prov_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagingidentity",
            index=models.Index(
                fields=["user", "provider", "status"],
                name="msg_identity_user_provider_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagingidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_user_id"),
                name="msg_ident_provider_user_u",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagingidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chat_id", ""), _negated=True),
                fields=("provider", "chat_id"),
                name="msg_ident_provider_chat_u",
            ),
        ),
        migrations.AddIndex(
            model_name="messagingaccountconnection",
            index=models.Index(
                fields=["user", "provider", "status"], name="msg_conn_user_provider_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagingaccountconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("identity",),
                name="uniq_msg_active_conn_identity",
            ),
        ),
        migrations.AddIndex(
            model_name="messagingtoken",
            index=models.Index(
                fields=["purpose", "expires_at"], name="msg_token_purpose_exp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagingtoken",
            index=models.Index(
                fields=["user", "purpose", "used_at"], name="msg_token_user_purpose_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagingtoken",
            index=models.Index(
                fields=["identity", "purpose", "used_at"], name="msg_token_identity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagingactionexecution",
            index=models.Index(
                fields=["action_key", "status", "created_at"],
                name="msg_action_key_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagingactionexecution",
            index=models.Index(
                fields=["user", "action_key", "created_at"], name="msg_action_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagingwebhookevent",
            index=models.Index(
                fields=["provider", "status", "received_at"],
                name="msg_hook_prov_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagingwebhookevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_id", ""), _negated=True),
                fields=("provider", "event_id"),
                name="msg_hook_provider_event_u",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagingwebhookevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("update_id", ""), _negated=True),
                fields=("provider", "update_id"),
                name="msg_hook_provider_update_u",
            ),
        ),
    ]
