from __future__ import annotations

from copy import deepcopy

APP_API_V1_CONTRACT = {
    "contract_id": "loomera-app-api-v1-a7",
    "api_version": "v1",
    "status": "local_complete",
    "payment_policy": {
        "online_payment_enabled_for_booking_api": False,
        "supported_booking_payment_methods": ["pay_in_salon"],
        "creates_payment_on_confirm": False,
        "changes_wallet_on_confirm": False,
        "sends_notification_on_confirm": False,
    },
    "auth_policy": {
        "session_based": True,
        "otp_login": True,
        "csrf_required_for_api_session_posts": False,
        "customer_only_endpoints": [
            "booking_draft_validate",
            "booking_draft_summary",
            "booking_confirm",
            "my_appointments",
            "my_appointment_detail",
        ],
    },
    "response_shape": {
        "success": {
            "ok": True,
            "data": {},
        },
        "error": {
            "ok": False,
            "error": {
                "code": "string",
                "message": "string",
            },
        },
    },
    "pagination_shape": {
        "limit": "integer",
        "offset": "integer",
        "count": "integer",
        "total_count": "integer",
        "has_next": "boolean",
    },
    "endpoints": [
        {
            "id": "health",
            "method": "GET",
            "path": "/api/v1/health/",
            "path_example": "/api/v1/health/",
            "auth_required": False,
            "purpose": "API health check.",
            "request_body": None,
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [],
        },
        {
            "id": "meta",
            "method": "GET",
            "path": "/api/v1/meta/",
            "path_example": "/api/v1/meta/",
            "auth_required": False,
            "purpose": "Public API/app metadata.",
            "request_body": None,
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [],
        },
        {
            "id": "public_salons",
            "method": "GET",
            "path": "/api/v1/salons/",
            "path_example": "/api/v1/salons/",
            "auth_required": False,
            "purpose": "List public active salons.",
            "request_body": None,
            "query_params": ["q", "limit", "offset"],
            "success_status": 200,
            "primary_error_codes": ["query_too_large"],
        },
        {
            "id": "public_salon_detail",
            "method": "GET",
            "path": "/api/v1/salons/<salon_slug>/",
            "path_example": "/api/v1/salons/readiness-salon/",
            "auth_required": False,
            "purpose": "Read public salon profile.",
            "request_body": None,
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": ["salon_not_found"],
        },
        {
            "id": "public_salon_services",
            "method": "GET",
            "path": "/api/v1/salons/<salon_slug>/services/",
            "path_example": "/api/v1/salons/readiness-salon/services/",
            "auth_required": False,
            "purpose": "List active services for a salon.",
            "request_body": None,
            "query_params": ["q", "limit", "offset"],
            "success_status": 200,
            "primary_error_codes": ["salon_not_found", "query_too_large"],
        },
        {
            "id": "public_salon_stylists",
            "method": "GET",
            "path": "/api/v1/salons/<salon_slug>/stylists/",
            "path_example": "/api/v1/salons/readiness-salon/stylists/",
            "auth_required": False,
            "purpose": "List visible stylists for a salon.",
            "request_body": None,
            "query_params": ["service_id", "limit", "offset"],
            "success_status": 200,
            "primary_error_codes": ["salon_not_found", "query_too_large"],
        },
        {
            "id": "public_services",
            "method": "GET",
            "path": "/api/v1/services/",
            "path_example": "/api/v1/services/",
            "auth_required": False,
            "purpose": "Global active service catalog.",
            "request_body": None,
            "query_params": ["q", "salon_slug", "limit", "offset"],
            "success_status": 200,
            "primary_error_codes": ["query_too_large"],
        },
        {
            "id": "availability",
            "method": "GET",
            "path": "/api/v1/salons/<salon_slug>/availability/",
            "path_example": "/api/v1/salons/readiness-salon/availability/",
            "auth_required": False,
            "purpose": "Read available slots for one service/date.",
            "request_body": None,
            "query_params": ["service_id", "date", "stylist_id"],
            "success_status": 200,
            "primary_error_codes": [
                "salon_not_found",
                "service_not_found",
                "invalid_date",
                "date_out_of_range",
            ],
        },
        {
            "id": "next_available",
            "method": "GET",
            "path": "/api/v1/salons/<salon_slug>/next-available/",
            "path_example": "/api/v1/salons/readiness-salon/next-available/",
            "auth_required": False,
            "purpose": "Find next available slots from a start date.",
            "request_body": None,
            "query_params": ["service_id", "date", "days", "stylist_id"],
            "success_status": 200,
            "primary_error_codes": [
                "salon_not_found",
                "service_not_found",
                "invalid_date",
                "date_out_of_range",
            ],
        },
        {
            "id": "auth_status",
            "method": "GET",
            "path": "/api/v1/auth/status/",
            "path_example": "/api/v1/auth/status/",
            "auth_required": False,
            "purpose": "Read current session authentication status.",
            "request_body": None,
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [],
        },
        {
            "id": "auth_me",
            "method": "GET",
            "path": "/api/v1/auth/me/",
            "path_example": "/api/v1/auth/me/",
            "auth_required": True,
            "purpose": "Read current authenticated user profile.",
            "request_body": None,
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": ["authentication_required"],
        },
        {
            "id": "auth_policy",
            "method": "GET",
            "path": "/api/v1/auth/policy/",
            "path_example": "/api/v1/auth/policy/",
            "auth_required": False,
            "purpose": "Read auth/OTP policy for app clients.",
            "request_body": None,
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [],
        },
        {
            "id": "otp_request",
            "method": "POST",
            "path": "/api/v1/auth/otp/request/",
            "path_example": "/api/v1/auth/otp/request/",
            "auth_required": False,
            "purpose": "Request OTP for Iranian mobile login.",
            "request_body": {
                "mobile": "09120000000",
            },
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [
                "invalid_mobile",
                "otp_resend_too_soon",
                "otp_rate_limited",
                "otp_rate_limit_unavailable",
                "payload_too_large",
            ],
        },
        {
            "id": "otp_verify",
            "method": "POST",
            "path": "/api/v1/auth/otp/verify/",
            "path_example": "/api/v1/auth/otp/verify/",
            "auth_required": False,
            "purpose": "Verify OTP and create authenticated session.",
            "request_body": {
                "mobile": "09120000000",
                "code": "123456",
            },
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [
                "invalid_mobile",
                "invalid_otp_code",
                "otp_not_found",
                "otp_expired",
                "otp_invalid",
                "otp_max_attempts_exceeded",
                "auth_user_not_found",
            ],
        },
        {
            "id": "auth_logout",
            "method": "POST",
            "path": "/api/v1/auth/logout/",
            "path_example": "/api/v1/auth/logout/",
            "auth_required": False,
            "purpose": "Clear current session.",
            "request_body": {},
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [],
        },
        {
            "id": "booking_draft_validate",
            "method": "POST",
            "path": "/api/v1/bookings/draft/validate/",
            "path_example": "/api/v1/bookings/draft/validate/",
            "auth_required": True,
            "purpose": "Validate a booking draft without creating anything.",
            "request_body": {
                "salon_slug": "local-seed-salon-1",
                "service_id": 1,
                "stylist_id": 1,
                "date": "2026-07-10",
                "start_time": "10:00",
            },
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [
                "authentication_required",
                "customer_profile_required",
                "salon_not_found",
                "service_not_found",
                "stylist_not_found",
                "invalid_date",
                "date_out_of_range",
                "invalid_start_time",
                "payload_too_large",
            ],
        },
        {
            "id": "booking_draft_summary",
            "method": "POST",
            "path": "/api/v1/bookings/draft/summary/",
            "path_example": "/api/v1/bookings/draft/summary/",
            "auth_required": True,
            "purpose": "Return booking price/summary without creating anything.",
            "request_body": {
                "salon_slug": "local-seed-salon-1",
                "service_id": 1,
                "stylist_id": 1,
                "date": "2026-07-10",
                "start_time": "10:00",
            },
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [
                "authentication_required",
                "customer_profile_required",
                "slot_unavailable",
                "payload_too_large",
            ],
        },
        {
            "id": "booking_confirm",
            "method": "POST",
            "path": "/api/v1/bookings/confirm/",
            "path_example": "/api/v1/bookings/confirm/",
            "auth_required": True,
            "purpose": "Create pay-in-salon booking order and appointment.",
            "request_body": {
                "salon_slug": "local-seed-salon-1",
                "service_id": 1,
                "stylist_id": 1,
                "date": "2026-07-10",
                "start_time": "10:00",
                "payment_method": "pay_in_salon",
            },
            "query_params": [],
            "success_status": 201,
            "primary_error_codes": [
                "authentication_required",
                "customer_profile_required",
                "unsupported_payment_method",
                "salon_not_found",
                "service_not_found",
                "stylist_not_found",
                "invalid_date",
                "date_out_of_range",
                "invalid_start_time",
                "slot_unavailable",
                "payload_too_large",
            ],
            "side_effects": {
                "creates_order": True,
                "creates_order_detail": True,
                "creates_payment": False,
                "changes_wallet": False,
                "sends_notification": False,
            },
        },
        {
            "id": "my_appointments",
            "method": "GET",
            "path": "/api/v1/me/appointments/",
            "path_example": "/api/v1/me/appointments/",
            "auth_required": True,
            "purpose": "List current customer's own appointments.",
            "request_body": None,
            "query_params": ["limit", "offset"],
            "success_status": 200,
            "primary_error_codes": [
                "authentication_required",
                "customer_profile_required",
                "query_too_large",
            ],
        },
        {
            "id": "my_appointment_detail",
            "method": "GET",
            "path": "/api/v1/me/appointments/<appointment_id>/",
            "path_example": "/api/v1/me/appointments/1/",
            "auth_required": True,
            "purpose": "Read current customer's own appointment detail.",
            "request_body": None,
            "query_params": [],
            "success_status": 200,
            "primary_error_codes": [
                "authentication_required",
                "customer_profile_required",
                "appointment_not_found",
            ],
        },
    ],
    "handoff_notes": [
        "All booking write operations are limited to pay_in_salon.",
        "Online payment is intentionally out of scope for this API phase.",
        "Appointment cancel/reschedule is intentionally out of scope for this API phase.",
        "Customer-only endpoints must use authenticated Django session.",
        "Do not expose customer/stylist mobile numbers or emails in public/app booking responses.",
    ],
}


def get_app_api_v1_contract():
    return deepcopy(APP_API_V1_CONTRACT)


def get_app_api_v1_endpoint(endpoint_id: str):
    endpoint_id = str(endpoint_id or "").strip()
    for endpoint in APP_API_V1_CONTRACT["endpoints"]:
        if endpoint["id"] == endpoint_id:
            return deepcopy(endpoint)
    return None
