# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
import django.utils.timezone
import utils
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("salons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(max_length=100, verbose_name="نام ویژگی "),
                ),
            ],
            options={
                "verbose_name": "ویژگی",
                "verbose_name_plural": "ویژگی ها",
                "db_table": "s_feature",
            },
        ),
        migrations.CreateModel(
            name="FeatureValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_title",
                    models.CharField(max_length=100, verbose_name="عنوان مقدار"),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_values",
                        to="services.feature",
                        verbose_name="ویژگی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدار ویژگی",
                "verbose_name_plural": "مقادیر ویژگی ها ",
            },
        ),
        migrations.CreateModel(
            name="GroupServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_title",
                    models.CharField(max_length=50, verbose_name="عنوان گروه خدمات "),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=160,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=220,
                        verbose_name="توضیحات SEO",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Canonical URL"
                    ),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(default=True, verbose_name="اجازه ایندکس SEO"),
                ),
                (
                    "group_image",
                    models.ImageField(
                        upload_to=utils.File_Uploader("images", "GroupServices"),
                        verbose_name="تصویر گروه خدمات",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات گروه خدمات "
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="وضعیت فعال/ غیرفعال"
                    ),
                ),
                (
                    "registere_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان انتشار "
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان آخرین ویرایش"
                    ),
                ),
                (
                    "group_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="services.groupservices",
                        verbose_name="والد گروه خدمات",
                    ),
                ),
            ],
            options={
                "verbose_name": "گروه خدمات",
                "verbose_name_plural": "گروه های خدمات ",
                "db_table": "s_groupservices",
            },
        ),
        migrations.AddField(
            model_name="feature",
            name="product_group",
            field=models.ManyToManyField(
                related_name="features_of_groups",
                to="services.groupservices",
                verbose_name="گروه خدمات",
            ),
        ),
        migrations.CreateModel(
            name="MaterialItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="نام ماده مصرفی"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "عدد"),
                            ("gram", "گرم"),
                            ("milliliter", "میلی\u200cلیتر"),
                            ("session", "نوبت"),
                            ("other", "سایر"),
                        ],
                        default="piece",
                        max_length=20,
                        verbose_name="واحد",
                    ),
                ),
                (
                    "default_unit_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="مبلغ به تومان",
                        verbose_name="هزینه پیش\u200cفرض هر واحد",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="کد داخلی / SKU",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_items",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
            ],
            options={
                "verbose_name": "ماده مصرفی",
                "verbose_name_plural": "مواد مصرفی",
                "db_table": "s_material_item",
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="مقدار")),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.feature",
                        verbose_name="ویژگی",
                    ),
                ),
                (
                    "filter_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.featurevalue",
                        verbose_name="مقدار فیلتر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی خدمات",
                "verbose_name_plural": "ویژگی های خدمات",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=500, verbose_name="نام خدمات"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=220,
                        verbose_name="توضیحات SEO",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Canonical URL"
                    ),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(default=True, verbose_name="اجازه ایندکس SEO"),
                ),
                (
                    "summery_description",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="توضیحات خلاصه خدمات",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات کامل خدمات"
                    ),
                ),
                (
                    "service_image",
                    models.ImageField(
                        null=True,
                        upload_to=utils.File_Uploader("images", "services"),
                        verbose_name="تصویر خدمات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        null=True,
                        verbose_name="وضعیت فعال / غیرفعال",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="مدت زمان خدمت (دقیقه)"
                    ),
                ),
                (
                    "base_price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="این قیمت پایه حتی قبل از اتصال عضو تیم به خدمت نگهداری می\u200cشود.",
                        verbose_name="قیمت پایه خدمت (تومان)",
                    ),
                ),
                (
                    "buffer_minutes",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="این زمان بعد از پایان خدمت برای آماده\u200cسازی، جمع\u200cبندی و جلوگیری از تداخل نوبت بعدی رزرو می\u200cشود.",
                        verbose_name="بافر تاخیر/آماده\u200cسازی بعد از خدمت (دقیقه)",
                    ),
                ),
                (
                    "registere_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان آخرین ویرایش"
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        through="services.ServiceFeature", to="services.feature"
                    ),
                ),
                (
                    "service_group",
                    models.ManyToManyField(
                        related_name="services_of_group",
                        to="services.groupservices",
                        verbose_name="گروه خدمات",
                    ),
                ),
                (
                    "stylists",
                    models.ManyToManyField(
                        related_name="services_of_stylist",
                        to="accounts.stylist",
                        verbose_name="آرایشگران",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمات",
                "verbose_name_plural": "خدمات",
                "db_table": "s_services",
            },
        ),
        migrations.CreateModel(
            name="ServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="قیمت")),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stylist_prices",
                        to="accounts.stylist",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_prices",
                        to="services.services",
                    ),
                ),
            ],
            options={
                "verbose_name": "قیمت خدمت",
                "verbose_name_plural": "قیمت های خدمت",
            },
        ),
        migrations.CreateModel(
            name="ServiceMaterialTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="مقدار پیش\u200cفرض مصرف",
                    ),
                ),
                (
                    "unit_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="اگر صفر باشد، از هزینه پیش\u200cفرض ماده مصرفی استفاده می\u200cشود.",
                        verbose_name="هزینه هر واحد",
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("salon", "هزینه با سالن"),
                            ("stylist", "هزینه با آرایشگر"),
                            ("shared", "هزینه مشترک"),
                        ],
                        default="salon",
                        max_length=20,
                        verbose_name="پرداخت\u200cکننده هزینه مواد",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_templates",
                        to="services.materialitem",
                        verbose_name="ماده مصرفی",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_material_templates",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_templates",
                        to="services.services",
                        verbose_name="خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب مواد مصرفی خدمت",
                "verbose_name_plural": "قالب\u200cهای مواد مصرفی خدمات",
                "db_table": "s_service_material_template",
            },
        ),
        migrations.CreateModel(
            name="ServiceGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_image",
                    models.ImageField(
                        null=True,
                        upload_to=utils.File_Uploader("images", "services_gallery"),
                        verbose_name="تصویر خدمات",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="services.services",
                        verbose_name="خدمات",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر خدمات",
                "verbose_name_plural": "تصاویر خدمات",
            },
        ),
        migrations.AddField(
            model_name="servicefeature",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_features",
                to="services.services",
                verbose_name="خدمات",
            ),
        ),
        migrations.CreateModel(
            name="StylistCommissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")],
                        default="percent",
                        max_length=20,
                        verbose_name="نوع سهم",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="درصد سهم آرایشگر",
                    ),
                ),
                (
                    "fixed_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ ثابت سهم آرایشگر"
                    ),
                ),
                (
                    "share_base",
                    models.CharField(
                        choices=[
                            ("gross_after_discount", "بعد از تخفیف"),
                            ("after_platform_commission", "بعد از کارمزد پلتفرم"),
                            ("net_after_materials", "سود خالص بعد از مواد"),
                        ],
                        default="net_after_materials",
                        max_length=32,
                        verbose_name="مبنای محاسبه سهم",
                    ),
                ),
                (
                    "material_cost_policy",
                    models.CharField(
                        choices=[
                            ("salon_pays", "هزینه مواد با سالن"),
                            ("stylist_pays", "هزینه مواد با آرایشگر"),
                            ("split", "هزینه مواد مشترک"),
                        ],
                        default="salon_pays",
                        max_length=20,
                        verbose_name="سیاست هزینه مواد",
                    ),
                ),
                (
                    "stylist_material_cost_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="فقط وقتی سیاست هزینه مواد مشترک باشد استفاده می\u200cشود.",
                        max_digits=5,
                        verbose_name="درصد هزینه مواد با آرایشگر",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(blank=True, null=True, verbose_name="شروع اعتبار"),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="پایان اعتبار"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stylist_commission_rules",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="services.services",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="accounts.stylist",
                        verbose_name="آرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "قانون سهم آرایشگر",
                "verbose_name_plural": "قوانین سهم آرایشگران",
                "db_table": "s_stylist_commission_rule",
            },
        ),
        migrations.AddIndex(
            model_name="materialitem",
            index=models.Index(
                fields=["salon", "is_active"], name="mat_salon_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialitem",
            constraint=models.UniqueConstraint(
                fields=("salon", "name"), name="unique_material_name_per_salon"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_unit_cost__gte", 0)),
                name="mat_def_unit_cost_gte0",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceprice",
            unique_together={("service", "stylist")},
        ),
        migrations.AddIndex(
            model_name="servicematerialtemplate",
            index=models.Index(
                fields=["salon", "service", "is_active"], name="svc_mat_tpl_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicematerialtemplate",
            constraint=models.UniqueConstraint(
                fields=("salon", "service", "material"), name="uniq_mat_tpl_service"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicematerialtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_quantity__gte", 0)),
                name="service_material_qty_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicematerialtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)), name="srv_mat_unit_cost_gte0"
            ),
        ),
        migrations.AddIndex(
            model_name="stylistcommissionrule",
            index=models.Index(
                fields=["salon", "service", "stylist", "is_active"],
                name="sty_comm_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stylistcommissionrule",
            index=models.Index(
                fields=["effective_from", "effective_to"], name="sty_comm_dates_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stylistcommissionrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("percent__gte", 0), ("percent__lte", 100)),
                name="sty_comm_pct_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="stylistcommissionrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("fixed_amount__gte", 0)), name="sty_comm_fixed_gte0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stylistcommissionrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stylist_material_cost_percent__gte", 0),
                    ("stylist_material_cost_percent__lte", 100),
                ),
                name="stylist_material_percent_range",
            ),
        ),
    ]
