# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("salons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="کلیدواژه"
                    ),
                ),
                (
                    "normalized_keyword",
                    models.CharField(
                        db_index=True,
                        max_length=120,
                        verbose_name="کلیدواژه نرمال\u200cشده",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("service", "خدمت"),
                            ("group", "دسته خدمت"),
                            ("salon", "سالن"),
                        ],
                        max_length=32,
                        verbose_name="نوع مقصد",
                    ),
                ),
                ("target_id", models.PositiveIntegerField(verbose_name="شناسه مقصد")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="فعال"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "معادل جستجو",
                "verbose_name_plural": "معادل\u200cهای جستجو",
                "indexes": [
                    models.Index(
                        fields=["normalized_keyword", "is_active"],
                        name="srchalias_norm_act_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="کلید نشست"
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="عبارت جستجو",
                    ),
                ),
                (
                    "normalized_query",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="عبارت نرمال\u200cشده",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="موقعیت"
                    ),
                ),
                (
                    "q_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="نوع پیشنهاد انتخاب\u200cشده",
                    ),
                ),
                (
                    "q_id",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="شناسه پیشنهاد انتخاب\u200cشده",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="فیلترها"),
                ),
                (
                    "sort",
                    models.CharField(
                        blank=True,
                        default="recommended",
                        max_length=64,
                        verbose_name="مرتب\u200cسازی",
                    ),
                ),
                (
                    "results_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد نتایج"),
                ),
                (
                    "no_result",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="بدون نتیجه"
                    ),
                ),
                (
                    "first_result_salon_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="اولین نتیجه"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ثبت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ جستجو",
                "verbose_name_plural": "لاگ\u200cهای جستجو",
            },
        ),
        migrations.CreateModel(
            name="SearchConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion_type",
                    models.CharField(
                        default="booking_started",
                        max_length=64,
                        verbose_name="نوع تبدیل",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ثبت"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_conversions",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_conversions",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_conversions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "search_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="search.searchlog",
                        verbose_name="لاگ جستجو",
                    ),
                ),
            ],
            options={
                "verbose_name": "تبدیل جستجو",
                "verbose_name_plural": "تبدیل\u200cهای جستجو",
            },
        ),
        migrations.CreateModel(
            name="SearchResultClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=0, verbose_name="رتبه در نتایج"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="search", max_length=64, verbose_name="منبع"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ثبت"
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_clicks",
                        to="salons.salon",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "search_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clicks",
                        to="search.searchlog",
                        verbose_name="لاگ جستجو",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_result_clicks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلیک نتیجه جستجو",
                "verbose_name_plural": "کلیک\u200cهای نتیجه جستجو",
            },
        ),
        migrations.AddIndex(
            model_name="searchlog",
            index=models.Index(fields=["created_at"], name="srchlog_created_idx"),
        ),
        migrations.AddIndex(
            model_name="searchlog",
            index=models.Index(
                fields=["no_result", "created_at"], name="srchlog_nores_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchlog",
            index=models.Index(fields=["normalized_query"], name="srchlog_normq_idx"),
        ),
        migrations.AddIndex(
            model_name="searchconversion",
            index=models.Index(
                fields=["conversion_type", "created_at"], name="srchconv_type_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchconversion",
            index=models.Index(
                fields=["salon", "created_at"], name="srchconv_salon_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchresultclick",
            index=models.Index(
                fields=["salon", "created_at"], name="srchclk_salon_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchresultclick",
            index=models.Index(
                fields=["search_log", "created_at"], name="srchclk_log_dt_idx"
            ),
        ),
    ]
