# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iban", models.CharField(max_length=34, verbose_name="شماره شبا")),
                (
                    "account_owner_name",
                    models.CharField(max_length=255, verbose_name="نام صاحب حساب"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="نام بانک"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="تأیید شده"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تأیید"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="حساب پیش\u200cفرض"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "حساب بانکی سالن",
                "verbose_name_plural": "حساب\u200cهای بانکی سالن\u200cها",
                "db_table": "s_bank_accounts",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalonMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invited_phone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=32,
                        verbose_name="موبایل دعوت\u200cشده",
                    ),
                ),
                (
                    "invited_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="ایمیل دعوت\u200cشده",
                    ),
                ),
                (
                    "role_title",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="عنوان نقش"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "دعوت\u200cشده"),
                            ("pending_acceptance", "در انتظار پذیرش"),
                            ("active", "فعال"),
                            ("paused", "موقتاً غیرفعال"),
                            ("ended", "قطع همکاری"),
                            ("rejected", "رد شده"),
                            ("expired", "منقضی شده"),
                            ("cancelled_by_salon", "لغو شده توسط سالن"),
                        ],
                        db_index=True,
                        default="invited",
                        max_length=64,
                        verbose_name="وضعیت همکاری",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پذیرش"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پایان همکاری"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انقضای دعوت"
                    ),
                ),
                (
                    "show_on_salon_profile",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در پروفایل سالن"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "عضویت آرایشگر در سالن",
                "verbose_name_plural": "عضویت\u200cهای آرایشگران در سالن\u200cها",
                "db_table": "s_salon_memberships",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalonOpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "شنبه"),
                            (2, "یکشنبه"),
                            (3, "دوشنبه"),
                            (4, "سه شنبه"),
                            (5, "چهارشنبه"),
                            (6, "پنج شنبه"),
                            (7, "جمعه"),
                        ],
                        verbose_name="روز هفته",
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(blank=True, null=True, verbose_name="ساعت شروع"),
                ),
                (
                    "close_time",
                    models.TimeField(blank=True, null=True, verbose_name="ساعت پایان"),
                ),
                ("is_closed", models.BooleanField(default=False, verbose_name="تعطیل")),
            ],
            options={
                "verbose_name": "ساعت کاری سالن",
                "verbose_name_plural": "ساعت کاری سالن\u200cها",
                "db_table": "s_salon_opening_hours",
            },
        ),
        migrations.CreateModel(
            name="SalonsGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salon_image",
                    models.ImageField(
                        upload_to=utils.File_Uploader("images", "salon_gallery"),
                        verbose_name="تصویر سالن",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="تصویر کاور"),
                ),
            ],
            options={
                "verbose_name": "تصویر سالن",
                "verbose_name_plural": "تصاویر سالن ها ",
                "db_table": "salons_gallery",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SalonVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "تأیید نشده"),
                            ("profile_incomplete", "پروفایل ناقص"),
                            ("documents_pending", "در انتظار ارسال مدارک"),
                            ("under_review", "در حال بررسی"),
                            ("verified", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("suspended", "تعلیق شده"),
                            ("expired", "نیازمند تمدید مدارک"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=64,
                        verbose_name="وضعیت احراز",
                    ),
                ),
                (
                    "identity_status",
                    models.CharField(
                        default="not_submitted",
                        max_length=64,
                        verbose_name="وضعیت مدارک هویتی",
                    ),
                ),
                (
                    "business_info_status",
                    models.CharField(
                        default="not_submitted",
                        max_length=64,
                        verbose_name="وضعیت اطلاعات کسب\u200cوکار",
                    ),
                ),
                (
                    "license_status",
                    models.CharField(
                        default="not_required", max_length=64, verbose_name="وضعیت مجوز"
                    ),
                ),
                (
                    "bank_account_status",
                    models.CharField(
                        default="not_submitted",
                        max_length=64,
                        verbose_name="وضعیت حساب بانکی",
                    ),
                ),
                (
                    "contract_status",
                    models.CharField(
                        default="not_signed",
                        max_length=64,
                        verbose_name="وضعیت قرارداد",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ بررسی"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, default="", verbose_name="دلیل رد"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "احراز سالن",
                "verbose_name_plural": "احراز سالن\u200cها",
                "db_table": "s_salon_verifications",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalonVerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("identity", "مدرک هویتی"),
                            ("business_license", "جواز یا مجوز فعالیت"),
                            ("bank", "مدرک حساب بانکی"),
                            ("contract", "قرارداد"),
                            ("other", "سایر"),
                        ],
                        max_length=64,
                        verbose_name="نوع مدرک",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=utils.File_Uploader(
                            "documents", "salon_verification"
                        ),
                        verbose_name="فایل",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="pending",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ بررسی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "مدرک احراز سالن",
                "verbose_name_plural": "مدارک احراز سالن",
                "db_table": "s_salon_verification_documents",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalonVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ بازدید"
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید سالن",
                "verbose_name_plural": "بازدیدهای سالن",
                "db_table": "s_salon_visit",
            },
        ),
        migrations.CreateModel(
            name="StaffDashboardPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_complete_appointments",
                    models.BooleanField(default=True, verbose_name="اجرای مراحل نوبت"),
                ),
                (
                    "can_view_own_finance",
                    models.BooleanField(default=True, verbose_name="مشاهده مالی خود"),
                ),
                (
                    "can_request_payout",
                    models.BooleanField(
                        default=True, verbose_name="درخواست پرداخت سهم"
                    ),
                ),
                (
                    "can_view_own_clients",
                    models.BooleanField(
                        default=True, verbose_name="مشاهده مشتریان خود"
                    ),
                ),
                (
                    "can_create_own_bookings",
                    models.BooleanField(default=True, verbose_name="ثبت نوبت برای خود"),
                ),
                (
                    "can_view_client_phone",
                    models.BooleanField(
                        default=False, verbose_name="مشاهده شماره تماس مشتری"
                    ),
                ),
                (
                    "can_manage_own_portfolio",
                    models.BooleanField(
                        default=True, verbose_name="مدیریت نمونه\u200cکار خود"
                    ),
                ),
                (
                    "can_submit_posts",
                    models.BooleanField(
                        default=False, verbose_name="ارسال مقاله پیشنهادی"
                    ),
                ),
                (
                    "can_submit_stories",
                    models.BooleanField(
                        default=False, verbose_name="ارسال استوری پیشنهادی"
                    ),
                ),
                (
                    "can_request_leave",
                    models.BooleanField(default=True, verbose_name="درخواست مرخصی"),
                ),
                (
                    "can_manage_own_schedule",
                    models.BooleanField(
                        default=False, verbose_name="مدیریت برنامه کاری خود"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "دسترسی داشبورد آرایشگر",
                "verbose_name_plural": "دسترسی\u200cهای داشبورد آرایشگران",
                "db_table": "s_staff_dashboard_permissions",
            },
        ),
        migrations.CreateModel(
            name="SupplementaryInfoView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="عنوان")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader("images", "SupplementaryInfo"),
                        verbose_name="تصویر آیکون",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="کلاس آیکون"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
            ],
            options={
                "verbose_name": "اطلاعات تکمیلی",
                "verbose_name_plural": "اطلاعات تکمیلی",
                "db_table": "s_salon_supplementary_info",
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(verbose_name="یادداشت")),
                (
                    "note_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader("images", "customer_note"),
                        verbose_name="تصویر یادداشت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_note_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد کننده",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_note",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشت مشتری",
                "verbose_name_plural": "یادداشت\u200cهای مشتری",
                "db_table": "s_customer_note",
            },
        ),
        migrations.CreateModel(
            name="MembershipEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="نوع رویداد"
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="وضعیت قبلی"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="وضعیت جدید"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اقدام\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد عضویت",
                "verbose_name_plural": "رویدادهای عضویت",
                "db_table": "s_membership_events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salon_name",
                    models.CharField(max_length=50, verbose_name="نام سالن"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="برای URL پایدار و قابل اشتراک سالن استفاده می\u200cشود.",
                        max_length=180,
                        unique=True,
                        verbose_name="اسلاگ سئویی",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=220,
                        verbose_name="توضیحات SEO",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Canonical URL"
                    ),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(default=True, verbose_name="اجازه ایندکس SEO"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/salons/og/",
                        verbose_name="تصویر Open Graph",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        default="salons_banner.jpg",
                        null=True,
                        upload_to=utils.File_Uploader("images", "salons_banner"),
                        verbose_name="بنر",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات ")),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=utils.File_Uploader("images", "salons_banner"),
                        verbose_name="ویدیو",
                    ),
                ),
                (
                    "zone",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="منطقه "
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="موقعیت جغرافیایی",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                (
                    "linkedin_link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="لینک لینکدین",
                    ),
                ),
                (
                    "insta_link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="لینک اینستا",
                    ),
                ),
                (
                    "telegram_link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="لینک تلگرام ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="وضعیت "),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "تأیید نشده"),
                            ("profile_incomplete", "پروفایل ناقص"),
                            ("documents_pending", "در انتظار ارسال مدارک"),
                            ("under_review", "در حال بررسی"),
                            ("verified", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("suspended", "تعلیق شده"),
                            ("expired", "نیازمند تمدید مدارک"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=64,
                        verbose_name="وضعیت احراز سالن",
                    ),
                ),
                (
                    "registere_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "phone_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="شماره تلفن "
                    ),
                ),
                (
                    "payout_iban",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=26,
                        verbose_name="شماره شبا برای تسویه",
                    ),
                ),
                (
                    "payout_account_holder_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="نام صاحب حساب برای تسویه",
                    ),
                ),
                (
                    "payout_bank_name",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="نام بانک"
                    ),
                ),
                (
                    "payout_contact_mobile",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=11,
                        verbose_name="شماره موبایل مسئول تسویه",
                    ),
                ),
                (
                    "cancellation_window_hours",
                    models.PositiveSmallIntegerField(
                        default=24, verbose_name="مهلت لغو آنلاین (ساعت)"
                    ),
                ),
                (
                    "cancellation_refund_percent",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="درصد بازگشت وجه به کیف پول"
                    ),
                ),
                (
                    "cancellation_policy_note",
                    models.TextField(
                        blank=True, default="", verbose_name="توضیحات سیاست لغو"
                    ),
                ),
                (
                    "payout_delay_days",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="تاخیر تسویه به سالن (روز)"
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_neighborhood",
                        to="locations.neighborhood",
                        verbose_name="محله",
                    ),
                ),
                (
                    "salon_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_manager",
                        to="accounts.salonmanager",
                        verbose_name="مدیر سالن ",
                    ),
                ),
            ],
            options={
                "verbose_name": "سالن",
                "verbose_name_plural": "سالن ها ",
                "db_table": "s_salon",
            },
        ),
    ]
