# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_initial"),
        ("salons", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="services",
            field=models.ManyToManyField(
                related_name="services_of_salon",
                to="services.services",
                verbose_name="خدمات ",
            ),
        ),
        migrations.AddField(
            model_name="salon",
            name="stylists",
            field=models.ManyToManyField(
                related_name="stylists_of_salon",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="customernote",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_notes",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="salonmembership",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_salon_membership_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دعوت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="salonmembership",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="salonmembership",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salon_memberships",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="membershipevent",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="salons.salonmembership",
                verbose_name="عضویت",
            ),
        ),
        migrations.AddField(
            model_name="salonopeninghours",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opening_hours",
                to="salons.salon",
                verbose_name="سالن مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="salonsgallery",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="salonverification",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_salon_verifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="بررسی\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="salonverification",
            name="salon",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="salonverificationdocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_salon_verification_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="بررسی\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="salonverificationdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_salon_verification_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="بارگذار",
            ),
        ),
        migrations.AddField(
            model_name="salonverificationdocument",
            name="verification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="salons.salonverification",
                verbose_name="پرونده احراز",
            ),
        ),
        migrations.AddField(
            model_name="salonvisit",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salon_visits",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="salonvisit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salon_visits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="staffdashboardpermission",
            name="membership",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_permissions",
                to="salons.salonmembership",
                verbose_name="عضویت",
            ),
        ),
        migrations.AddField(
            model_name="supplementaryinfoview",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplementary_info",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddIndex(
            model_name="customernote",
            index=models.Index(
                fields=["customer", "salon"], name="customer_salon_note_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["salon", "is_default"], name="s_bank_acco_salon_i_21033b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salonmembership",
            index=models.Index(
                fields=["salon", "status"], name="s_salon_mem_salon_i_a73ffe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salonmembership",
            index=models.Index(
                fields=["stylist", "status"], name="s_salon_mem_stylist_f1ad30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salonmembership",
            index=models.Index(
                fields=["invited_phone", "status"],
                name="s_salon_mem_invited_3fafe0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="salonmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stylist__isnull", False)),
                fields=("salon", "stylist"),
                name="uniq_salon_member_sty",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipevent",
            index=models.Index(
                fields=["membership", "-created_at"],
                name="s_membershi_members_1c0535_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salonvisit",
            unique_together={("user", "salon")},
        ),
    ]
