# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingPaymentPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("pay_at_venue", "پرداخت در محل"),
                            ("deposit_required", "بیعانه"),
                            ("full_online_payment", "پرداخت کامل آنلاین"),
                            ("bnpl_available", "پرداخت قسطی"),
                        ],
                        default="pay_at_venue",
                        max_length=64,
                        verbose_name="حالت پرداخت",
                    ),
                ),
                (
                    "deposit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed_amount", "مبلغ ثابت"),
                            ("percentage", "درصدی"),
                        ],
                        default="",
                        max_length=64,
                        verbose_name="نوع بیعانه",
                    ),
                ),
                (
                    "deposit_value",
                    models.PositiveIntegerField(default=0, verbose_name="مقدار بیعانه"),
                ),
                (
                    "min_deposit_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="حداقل بیعانه"
                    ),
                ),
                (
                    "max_deposit_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="حداکثر بیعانه"
                    ),
                ),
                (
                    "remaining_payment_method",
                    models.CharField(
                        default="pay_at_venue",
                        max_length=64,
                        verbose_name="روش پرداخت باقی\u200cمانده",
                    ),
                ),
                (
                    "customer_facing_text",
                    models.TextField(
                        blank=True, default="", verbose_name="متن قابل نمایش به مشتری"
                    ),
                ),
                (
                    "machine_rules",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="قوانین ماشینی"
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع اعتبار"
                    ),
                ),
                (
                    "effective_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان اعتبار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "قانون پرداخت رزرو",
                "verbose_name_plural": "قوانین پرداخت رزرو",
            },
        ),
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "free_cancellation_until_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="مهلت لغو رایگان"
                    ),
                ),
                (
                    "client_late_cancel_penalty_type",
                    models.CharField(
                        choices=[
                            ("none", "بدون جریمه"),
                            ("fixed_amount", "مبلغ ثابت"),
                            ("percentage_of_service_price", "درصد مبلغ خدمت"),
                            ("deposit_amount", "معادل بیعانه"),
                        ],
                        default="none",
                        max_length=64,
                        verbose_name="نوع جریمه مشتری",
                    ),
                ),
                (
                    "client_late_cancel_penalty_value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مقدار جریمه مشتری"
                    ),
                ),
                (
                    "no_show_penalty_type",
                    models.CharField(
                        choices=[
                            ("none", "بدون جریمه"),
                            ("fixed_amount", "مبلغ ثابت"),
                            ("percentage_of_service_price", "درصد مبلغ خدمت"),
                            ("deposit_amount", "معادل بیعانه"),
                        ],
                        default="none",
                        max_length=64,
                        verbose_name="نوع جریمه عدم حضور",
                    ),
                ),
                (
                    "no_show_penalty_value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مقدار جریمه عدم حضور"
                    ),
                ),
                (
                    "mirror_client_penalty_for_salon",
                    models.BooleanField(
                        default=True, verbose_name="اعمال متقارن برای سالن"
                    ),
                ),
                (
                    "salon_late_cancel_penalty_cap_type",
                    models.CharField(
                        choices=[
                            ("none", "بدون جریمه"),
                            ("fixed_amount", "مبلغ ثابت"),
                            ("percentage_of_service_price", "درصد مبلغ خدمت"),
                            ("deposit_amount", "معادل بیعانه"),
                        ],
                        default="percentage_of_service_price",
                        max_length=64,
                        verbose_name="نوع سقف جریمه سالن",
                    ),
                ),
                (
                    "salon_late_cancel_penalty_cap_value",
                    models.PositiveIntegerField(
                        default=30, verbose_name="مقدار سقف جریمه سالن"
                    ),
                ),
                (
                    "emergency_exception_allowed",
                    models.BooleanField(
                        default=True, verbose_name="امکان استثنای اضطراری"
                    ),
                ),
                (
                    "emergency_exception_requires_review",
                    models.BooleanField(
                        default=True, verbose_name="نیاز به بررسی استثنا"
                    ),
                ),
                (
                    "customer_facing_text",
                    models.TextField(
                        blank=True, default="", verbose_name="متن قابل نمایش به مشتری"
                    ),
                ),
                (
                    "machine_rules",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="قوانین ماشینی"
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع اعتبار"
                    ),
                ),
                (
                    "effective_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان اعتبار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "قانون لغو",
                "verbose_name_plural": "قوانین لغو",
            },
        ),
        migrations.CreateModel(
            name="CommissionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "applies_to_new_client_only",
                    models.BooleanField(default=True, verbose_name="فقط مشتری جدید"),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("percentage", "درصدی"),
                            ("fixed_amount", "مبلغ ثابت"),
                        ],
                        default="percentage",
                        max_length=32,
                        verbose_name="نوع کمیسیون",
                    ),
                ),
                (
                    "commission_value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مقدار کمیسیون"
                    ),
                ),
                (
                    "include_extra_charges",
                    models.BooleanField(
                        default=False, verbose_name="شامل هزینه\u200cهای اضافه"
                    ),
                ),
                (
                    "include_material_charges",
                    models.BooleanField(
                        default=False, verbose_name="شامل هزینه مواد دریافتی از مشتری"
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع اعتبار"
                    ),
                ),
                (
                    "effective_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان اعتبار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "سیاست کمیسیون پلتفرم",
                "verbose_name_plural": "سیاست\u200cهای کمیسیون پلتفرم",
            },
        ),
        migrations.CreateModel(
            name="CustomerCompensation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(verbose_name="مبلغ جبران")),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="دلیل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("credited", "اعتبار ثبت شد"),
                            ("paid", "پرداخت شد"),
                            ("cancelled", "لغو شد"),
                        ],
                        default="pending",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "اعتبار/جبران مشتری",
                "verbose_name_plural": "اعتبارها و جبران\u200cهای مشتری",
            },
        ),
        migrations.CreateModel(
            name="ExtraCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("amount", models.PositiveBigIntegerField(verbose_name="مبلغ")),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="دلیل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending_client_confirmation", "در انتظار تأیید مشتری"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("manager_approved", "تأیید مدیریتی"),
                        ],
                        default="draft",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "client_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید مشتری"
                    ),
                ),
                (
                    "manager_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید مدیریتی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "هزینه اضافه",
                "verbose_name_plural": "هزینه\u200cهای اضافه",
            },
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه مالک"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("salon", "حساب مالی سالن"),
                            ("staff_receivable", "مطالبات آرایشگر از سالن"),
                            ("platform_commission", "کمیسیون Loomera"),
                            ("salon_debt", "بدهی سالن به Loomera"),
                            ("client_compensation", "اعتبار جبرانی مشتری"),
                            ("provider_clearing", "حساب واسط provider پرداخت"),
                            ("refund", "برگشت وجه"),
                            ("adjustment", "اصلاحات مالی"),
                        ],
                        max_length=64,
                        verbose_name="نوع حساب",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IRR", max_length=8, verbose_name="واحد پول"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "حساب مالی داخلی",
                "verbose_name_plural": "حساب\u200cهای مالی داخلی",
            },
        ),
        migrations.CreateModel(
            name="FinancialAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="دلیل اصلاح")),
                ("amount", models.BigIntegerField(verbose_name="مبلغ اصلاح")),
                (
                    "target_field",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="فیلد هدف"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("applied", "اعمال شده"),
                        ],
                        default="pending",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان اعمال"
                    ),
                ),
            ],
            options={
                "verbose_name": "اصلاح مالی",
                "verbose_name_plural": "اصلاحات مالی",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_id",
                    models.UUIDField(db_index=True, verbose_name="شناسه گروه سند"),
                ),
                ("entry_type", models.CharField(max_length=64, verbose_name="نوع ثبت")),
                (
                    "direction",
                    models.CharField(
                        choices=[("debit", "بدهکار"), ("credit", "بستانکار")],
                        max_length=16,
                        verbose_name="جهت",
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(verbose_name="مبلغ")),
                (
                    "currency",
                    models.CharField(
                        default="IRR", max_length=8, verbose_name="واحد پول"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("posted", "ثبت\u200cشده"),
                            ("voided", "باطل\u200cشده با سند اصلاحی"),
                        ],
                        default="posted",
                        max_length=32,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
            ],
            options={
                "verbose_name": "ثبت دفتر مالی",
                "verbose_name_plural": "ثبت\u200cهای دفتر مالی",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderDetailFinancialSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="روش پرداخت"
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="درگاه پرداخت",
                    ),
                ),
                (
                    "gross_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ خام خدمت"
                    ),
                ),
                (
                    "discount_allocated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تخفیف تخصیص\u200cیافته"
                    ),
                ),
                (
                    "paid_amount_allocated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ پرداخت\u200cشده تخصیص\u200cیافته"
                    ),
                ),
                (
                    "platform_commission_allocated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کارمزد پلتفرم تخصیص\u200cیافته"
                    ),
                ),
                (
                    "net_after_platform",
                    models.PositiveIntegerField(
                        default=0, verbose_name="خالص بعد از کارمزد پلتفرم"
                    ),
                ),
                (
                    "material_cost_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کل هزینه مواد"
                    ),
                ),
                (
                    "material_cost_paid_by_salon",
                    models.PositiveIntegerField(
                        default=0, verbose_name="هزینه مواد با سالن"
                    ),
                ),
                (
                    "material_cost_paid_by_stylist",
                    models.PositiveIntegerField(
                        default=0, verbose_name="هزینه مواد با آرایشگر"
                    ),
                ),
                (
                    "share_base_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبنای محاسبه سهم"
                    ),
                ),
                (
                    "stylist_gross_share",
                    models.PositiveIntegerField(
                        default=0, verbose_name="سهم ناخالص آرایشگر"
                    ),
                ),
                (
                    "stylist_material_deduction",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کسر هزینه مواد از آرایشگر"
                    ),
                ),
                (
                    "stylist_net_share",
                    models.PositiveIntegerField(
                        default=0, verbose_name="سهم خالص آرایشگر"
                    ),
                ),
                (
                    "salon_gross_share",
                    models.PositiveIntegerField(
                        default=0, verbose_name="سهم ناخالص سالن"
                    ),
                ),
                (
                    "salon_material_deduction",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کسر هزینه مواد از سالن"
                    ),
                ),
                (
                    "salon_net_share",
                    models.PositiveIntegerField(
                        default=0, verbose_name="سهم خالص سالن"
                    ),
                ),
                (
                    "salon_net_profit",
                    models.PositiveIntegerField(
                        default=0, verbose_name="سود خالص سالن"
                    ),
                ),
                (
                    "extra_charges_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="هزینه\u200cهای اضافه تأییدشده"
                    ),
                ),
                (
                    "total_customer_paid",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کل مبلغ پرداخت/ثبت\u200cشده مشتری"
                    ),
                ),
                (
                    "salon_customer_compensation",
                    models.PositiveIntegerField(
                        default=0, verbose_name="جبران مشتری توسط سالن"
                    ),
                ),
                (
                    "salon_refund_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ برگشت وجه"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("finalized", "نهایی\u200cشده"),
                            ("reversed", "برگشت\u200cخورده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت سند مالی",
                    ),
                ),
                (
                    "rule_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="اسنپ\u200cشات قانون سهم"
                    ),
                ),
                (
                    "material_snapshot",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="اسنپ\u200cشات مواد مصرفی",
                    ),
                ),
                (
                    "calculation_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="جزئیات محاسبه"
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان نهایی شدن"
                    ),
                ),
                (
                    "reversed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان برگشت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "سند مالی آیتم رزرو",
                "verbose_name_plural": "اسناد مالی آیتم\u200cهای رزرو",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان پرداخت "
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان ویرایش پرداخت"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ پرداخت"
                    ),
                ),
                (
                    "is_finally",
                    models.BooleanField(default=False, verbose_name="وضعیت پرداخت"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("zarinpal", "زرین\u200cپال"),
                            ("zibal", "زیبال"),
                            ("wallet", "کیف پول"),
                            ("manual", "دستی"),
                            ("mock", "شبیه\u200cساز"),
                        ],
                        default="zarinpal",
                        max_length=20,
                        verbose_name="ارائه\u200cدهنده پرداخت",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("wallet", "کیف پول"), ("appointment", "رزرو")],
                        default="wallet",
                        max_length=20,
                        verbose_name="کاربری پرداخت",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("initiated", "شروع شده"),
                            ("pending", "در انتظار پرداخت"),
                            ("success", "موفق"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="initiated",
                        max_length=20,
                        verbose_name="وضعیت چرخه پرداخت",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات پرداخت")),
                (
                    "status_code",
                    models.IntegerField(blank=True, null=True, verbose_name="کد وضعیت"),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="شناسه نهایی پرداخت",
                    ),
                ),
                (
                    "gateway_track_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=80,
                        null=True,
                        verbose_name="شناسه رهگیری درگاه",
                    ),
                ),
                (
                    "callback_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="توکن بازگشت",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="کلید idempotency",
                    ),
                ),
                (
                    "sandbox_mode",
                    models.BooleanField(default=True, verbose_name="حالت تست"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تایید"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="فراداده پرداخت"
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت ها",
            },
        ),
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="نام provider")),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="کد provider"
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("psp", "پرداخت آنلاین"),
                            ("bnpl", "پرداخت قسطی"),
                            ("manual", "دستی"),
                        ],
                        max_length=64,
                        verbose_name="نوع provider",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="فعال")),
                (
                    "supports_deposit",
                    models.BooleanField(default=False, verbose_name="پشتیبانی بیعانه"),
                ),
                (
                    "supports_full_payment",
                    models.BooleanField(
                        default=False, verbose_name="پشتیبانی پرداخت کامل"
                    ),
                ),
                (
                    "supports_bnpl",
                    models.BooleanField(default=False, verbose_name="پشتیبانی BNPL"),
                ),
                (
                    "supports_refund",
                    models.BooleanField(
                        default=False, verbose_name="پشتیبانی برگشت وجه"
                    ),
                ),
                (
                    "supports_partial_refund",
                    models.BooleanField(
                        default=False, verbose_name="پشتیبانی برگشت جزئی"
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="تنظیمات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "ارائه\u200cدهنده پرداخت",
                "verbose_name_plural": "ارائه\u200cدهندگان پرداخت",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("pay_at_venue", "پرداخت در محل"),
                            ("online_card", "پرداخت آنلاین"),
                            ("deposit_online", "بیعانه آنلاین"),
                            ("bnpl_snapppay", "اسنپ\u200cپی"),
                            ("bnpl_digipay", "دیجی\u200cپی"),
                            ("bnpl_tara", "تارا"),
                        ],
                        max_length=64,
                        verbose_name="روش پرداخت",
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(verbose_name="مبلغ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "شروع شده"),
                            ("pending", "در انتظار"),
                            ("paid", "پرداخت شده"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغو شده"),
                            ("refunded", "برگشت داده شده"),
                            ("partially_refunded", "برگشت جزئی"),
                        ],
                        default="initiated",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="شناسه provider",
                    ),
                ),
                (
                    "provider_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="payload provider"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تراکنش پرداخت",
                "verbose_name_plural": "تراکنش\u200cهای پرداخت",
            },
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(verbose_name="مبلغ")),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="دلیل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("processing", "در حال پردازش"),
                            ("refunded", "برگشت داده شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "درخواست برگشت وجه",
                "verbose_name_plural": "درخواست\u200cهای برگشت وجه",
            },
        ),
        migrations.CreateModel(
            name="SalonPaymentProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                (
                    "min_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="حداقل مبلغ"
                    ),
                ),
                (
                    "max_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="حداکثر مبلغ"
                    ),
                ),
                (
                    "provider_commission_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="نوع کارمزد provider",
                    ),
                ),
                (
                    "provider_commission_value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مقدار کارمزد provider"
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="نوع تسویه"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تنظیم provider پرداخت سالن",
                "verbose_name_plural": "تنظیمات provider پرداخت سالن\u200cها",
            },
        ),
        migrations.CreateModel(
            name="SalonSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="روش پرداخت"
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="درگاه پرداخت",
                    ),
                ),
                (
                    "gross_services_amount",
                    models.PositiveIntegerField(default=0, verbose_name="جمع خدمات"),
                ),
                (
                    "discount_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مبلغ تخفیف"),
                ),
                (
                    "tax_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مالیات"),
                ),
                (
                    "paid_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ پرداخت\u200cشده"
                    ),
                ),
                (
                    "refund_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ بازگشت\u200cداده\u200cشده"
                    ),
                ),
                (
                    "first_visit_commission_applies",
                    models.BooleanField(
                        default=False, verbose_name="کارمزد اولین مراجعه"
                    ),
                ),
                (
                    "platform_commission_percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="درصد کارمزد"
                    ),
                ),
                (
                    "platform_commission_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مبلغ کارمزد"),
                ),
                (
                    "net_amount_due_to_salon",
                    models.PositiveIntegerField(
                        default=0, verbose_name="خالص قابل تسویه"
                    ),
                ),
                (
                    "payout_state",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "در انتظار پرداخت"),
                            ("manual_collection", "پرداخت در سالن"),
                            ("ready", "آماده تسویه"),
                            ("hold", "نیازمند بررسی"),
                            ("paid", "تسویه\u200cشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="awaiting_payment",
                        max_length=20,
                        verbose_name="وضعیت تسویه",
                    ),
                ),
                (
                    "payout_hold_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="دلیل نگه\u200cداری",
                    ),
                ),
                (
                    "eligible_for_payout_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان آمادگی تسویه"
                    ),
                ),
                (
                    "paid_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تسویه"
                    ),
                ),
                (
                    "policy_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="اسنپ\u200cشات قوانین"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "سند تسویه سالن",
                "verbose_name_plural": "اسناد تسویه سالن",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalonWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="موجودی قابل برداشت",
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="موجودی در انتظار تسویه",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "کیف پول مالی سالن",
                "verbose_name_plural": "کیف پول\u200cهای مالی سالن",
            },
        ),
        migrations.CreateModel(
            name="SalonWalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sale_pending", "ثبت فروش آنلاین"),
                            ("pending_release", "انتقال به موجودی قابل برداشت"),
                            ("refund_debit", "کسر بابت لغو/بازگشت وجه"),
                            ("withdraw_request", "درخواست دریافت"),
                            ("withdraw_restore", "بازگشت دریافت ردشده"),
                            ("manual_adjustment", "اصلاح دستی"),
                        ],
                        max_length=32,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                (
                    "pending_delta",
                    models.IntegerField(
                        default=0, verbose_name="تغییر موجودی در انتظار"
                    ),
                ),
                (
                    "available_delta",
                    models.IntegerField(
                        default=0, verbose_name="تغییر موجودی قابل برداشت"
                    ),
                ),
                (
                    "pending_balance_after",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="موجودی در انتظار بعد از تراکنش",
                    ),
                ),
                (
                    "available_balance_after",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="موجودی قابل برداشت بعد از تراکنش",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
            ],
            options={
                "verbose_name": "تراکنش کیف پول سالن",
                "verbose_name_plural": "تراکنش\u200cهای کیف پول سالن",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalonWalletWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ برداشت"
                    ),
                ),
                ("iban", models.CharField(max_length=26, verbose_name="شماره شبا")),
                (
                    "account_holder_name",
                    models.CharField(max_length=120, verbose_name="نام صاحب حساب"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="نام بانک"
                    ),
                ),
                (
                    "legacy_destination_iban",
                    models.CharField(
                        blank=True,
                        db_column="destination_iban",
                        default="",
                        editable=False,
                        max_length=26,
                        verbose_name="ستون سازگاری شبا",
                    ),
                ),
                (
                    "legacy_destination_account_holder_name",
                    models.CharField(
                        blank=True,
                        db_column="destination_account_holder_name",
                        default="",
                        editable=False,
                        max_length=120,
                        verbose_name="ستون سازگاری صاحب حساب",
                    ),
                ),
                (
                    "legacy_destination_bank_name",
                    models.CharField(
                        blank=True,
                        db_column="destination_bank_name",
                        default="",
                        editable=False,
                        max_length=80,
                        verbose_name="ستون سازگاری بانک",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "payment_receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="salon_wallet_withdrawal_receipts/",
                        verbose_name="رسید واریز",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "درخواست برداشت کیف پول سالن",
                "verbose_name_plural": "درخواست\u200cهای برداشت کیف پول سالن",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gross_share",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="سهم ناخالص"
                    ),
                ),
                (
                    "material_deduction",
                    models.PositiveBigIntegerField(default=0, verbose_name="کسر مواد"),
                ),
                (
                    "adjustments",
                    models.BigIntegerField(default=0, verbose_name="اصلاحات"),
                ),
                (
                    "net_profit",
                    models.BigIntegerField(default=0, verbose_name="سود خالص"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("payable", "قابل پرداخت"),
                            ("requested", "درخواست پرداخت شده"),
                            ("paid_by_salon", "پرداخت\u200cشده توسط سالن"),
                            ("disputed", "دارای اختلاف"),
                            ("adjusted", "اصلاح\u200cشده"),
                        ],
                        default="pending",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان محاسبه"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان درخواست"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "مطالبه آرایشگر",
                "verbose_name_plural": "مطالبات آرایشگران",
            },
        ),
        migrations.CreateModel(
            name="StaffPayoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_amount",
                    models.PositiveBigIntegerField(verbose_name="مبلغ درخواستی"),
                ),
                (
                    "approved_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="مبلغ تأیید شده"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("paid", "پرداخت شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=64,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "staff_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت آرایشگر"
                    ),
                ),
                (
                    "manager_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت مدیر"
                    ),
                ),
                (
                    "payment_receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="staff_payout_receipts/",
                        verbose_name="رسید پرداخت",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان درخواست"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تصمیم"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت"
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست پرداخت سهم آرایشگر",
                "verbose_name_plural": "درخواست\u200cهای پرداخت سهم آرایشگران",
            },
        ),
        migrations.CreateModel(
            name="StylistWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="مانده قابل دریافت",
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="موجودی در انتظار تسویه",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "حساب مالی آرایشگر",
                "verbose_name_plural": "حساب\u200cهای مالی آرایشگران",
            },
        ),
        migrations.CreateModel(
            name="StylistWalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("service_pending", "ثبت درآمد خدمت"),
                            ("pending_release", "انتقال به مانده قابل دریافت"),
                            ("reversal", "برگشت/اصلاح"),
                            ("withdraw_request", "درخواست دریافت"),
                            ("withdraw_restore", "بازگشت دریافت ردشده"),
                            ("manual_adjustment", "اصلاح دستی"),
                        ],
                        max_length=32,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                (
                    "pending_delta",
                    models.IntegerField(
                        default=0, verbose_name="تغییر موجودی در انتظار"
                    ),
                ),
                (
                    "available_delta",
                    models.IntegerField(
                        default=0, verbose_name="تغییر موجودی قابل برداشت"
                    ),
                ),
                (
                    "pending_balance_after",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="موجودی در انتظار بعد از تراکنش",
                    ),
                ),
                (
                    "available_balance_after",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="مانده قابل دریافت بعد از تراکنش",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
            ],
            options={
                "verbose_name": "تراکنش حساب مالی آرایشگر",
                "verbose_name_plural": "تراکنش\u200cهای حساب مالی آرایشگر",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StylistWalletWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ دریافت"
                    ),
                ),
                ("iban", models.CharField(max_length=26, verbose_name="شماره شبا")),
                (
                    "account_holder_name",
                    models.CharField(max_length=120, verbose_name="نام صاحب حساب"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="نام بانک"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "payment_receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="stylist_wallet_withdrawal_receipts/",
                        verbose_name="رسید واریز",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "درخواست دریافت درآمد آرایشگر",
                "verbose_name_plural": "درخواست\u200cهای دریافت درآمد آرایشگران",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="موجودی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کیف پول",
                "verbose_name_plural": "کیف پول\u200cها",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "واریز"),
                            ("WITHDRAW", "برداشت"),
                            ("PURCHASE", "خرید"),
                            ("REFUND", "بازگشت وجه"),
                            ("WITHDRAW_RESTORE", "بازگشت برداشت ردشده"),
                        ],
                        max_length=20,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ"
                    ),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="موجودی کیف پول بعد از انجام این تراکنش",
                        max_digits=10,
                        verbose_name="موجودی پس از تراکنش",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "تراکنش کیف پول",
                "verbose_name_plural": "تراکنش\u200cهای کیف پول",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ برداشت"
                    ),
                ),
                ("iban", models.CharField(max_length=26, verbose_name="شماره شبا")),
                (
                    "account_holder_name",
                    models.CharField(max_length=120, verbose_name="نام صاحب حساب"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="نام بانک"
                    ),
                ),
                (
                    "legacy_destination_iban",
                    models.CharField(
                        blank=True,
                        db_column="destination_iban",
                        default="",
                        editable=False,
                        max_length=26,
                        verbose_name="ستون سازگاری شبا",
                    ),
                ),
                (
                    "legacy_destination_account_holder_name",
                    models.CharField(
                        blank=True,
                        db_column="destination_account_holder_name",
                        default="",
                        editable=False,
                        max_length=120,
                        verbose_name="ستون سازگاری صاحب حساب",
                    ),
                ),
                (
                    "legacy_destination_bank_name",
                    models.CharField(
                        blank=True,
                        db_column="destination_bank_name",
                        default="",
                        editable=False,
                        max_length=80,
                        verbose_name="ستون سازگاری بانک",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "payment_receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="wallet_withdrawal_receipts/",
                        verbose_name="رسید واریز",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "درخواست برداشت کیف پول",
                "verbose_name_plural": "درخواست\u200cهای برداشت کیف پول",
                "ordering": ["-created_at"],
            },
        ),
    ]
