# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان مقاله "),
                ),
                ("summary", models.TextField(verbose_name="توضیحات  کوتاه ")),
                ("description", models.TextField(blank=True)),
                ("author", models.CharField(max_length=255, verbose_name="نویسنده")),
                (
                    "image",
                    models.ImageField(
                        default="images/Blogs/default.jfif",
                        upload_to=utils.File_Uploader("images", "blog"),
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "register_date",
                    models.DateField(auto_now=True, verbose_name="تاریخ درج "),
                ),
                (
                    "view_number",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                ("slug", models.SlugField(max_length=255, verbose_name="اسلاگ")),
            ],
            options={
                "verbose_name": "مقاله ",
                "verbose_name_plural": "مقالات ",
                "db_table": "B_blogs",
            },
        ),
        migrations.CreateModel(
            name="GroupBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_title",
                    models.CharField(max_length=255, verbose_name="عنوان گروه مقاله "),
                ),
            ],
            options={
                "verbose_name": "گروه مقاله ",
                "verbose_name_plural": "گروه های مقالات ",
            },
        ),
        migrations.CreateModel(
            name="BlogsGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=utils.File_Uploader("images", "Blogs"),
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Galleries",
                        to="blogs.blogs",
                        verbose_name="مقاله ",
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری مقاله ",
                "verbose_name_plural": "گالری مقالات",
            },
        ),
        migrations.AddField(
            model_name="blogs",
            name="group_blog",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="blogs.groupblog",
                verbose_name="گروه مقالات",
            ),
        ),
    ]
