# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(max_length=100, verbose_name="کد تخفیف "),
                ),
                ("start_date", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateTimeField(verbose_name="تاریخ پایان")),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="اگر صفر باشد، سقف مبلغی برای این کد در نظر گرفته نمی\u200cشود.",
                        verbose_name="سقف مبلغ تخفیف (تومان)",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "درصدی"),
                            ("fixed_amount", "مبلغ ثابت"),
                        ],
                        default="percentage",
                        max_length=32,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "discount_value",
                    models.PositiveIntegerField(default=0, verbose_name="مقدار تخفیف"),
                ),
                (
                    "min_order_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حداقل مبلغ رزرو"
                    ),
                ),
                (
                    "max_order_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حداکثر مبلغ رزرو"
                    ),
                ),
                (
                    "total_usage_limit",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حداکثر استفاده کل"
                    ),
                ),
                (
                    "per_customer_usage_limit",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حداکثر استفاده هر مشتری"
                    ),
                ),
                (
                    "first_booking_only",
                    models.BooleanField(
                        default=False, verbose_name="فقط اولین رزرو کاربر"
                    ),
                ),
                (
                    "first_salon_booking_only",
                    models.BooleanField(
                        default=False, verbose_name="فقط اولین رزرو کاربر در این سالن"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private_code", "کد خصوصی"),
                            ("public_code", "کد عمومی"),
                            ("search_badge", "نمایش در کارت و جستجو"),
                            ("checkout_only", "فقط در تسویه"),
                        ],
                        default="checkout_only",
                        max_length=32,
                        verbose_name="نوع نمایش",
                    ),
                ),
                (
                    "funded_by",
                    models.CharField(
                        choices=[
                            ("salon", "سالن"),
                            ("platform", "Loomera"),
                            ("shared", "مشترک"),
                        ],
                        default="salon",
                        max_length=32,
                        verbose_name="تأمین\u200cکننده هزینه",
                    ),
                ),
                (
                    "salon_funding_percent",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="درصد سهم سالن از هزینه تخفیف"
                    ),
                ),
                (
                    "platform_funding_percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="درصد سهم Loomera از هزینه تخفیف"
                    ),
                ),
                (
                    "stacking_policy",
                    models.CharField(
                        choices=[
                            ("not_stackable", "قابل ترکیب نیست"),
                            ("stack_with_service", "قابل ترکیب با تخفیف خدمت"),
                            ("stack_with_platform", "قابل ترکیب با کمپین پلتفرم"),
                            ("best_only", "فقط بهترین تخفیف"),
                        ],
                        default="stack_with_service",
                        max_length=32,
                        verbose_name="قانون ترکیب",
                    ),
                ),
                (
                    "staff_share_impact",
                    models.CharField(
                        choices=[
                            ("after_discount", "سهم از مبلغ بعد از تخفیف"),
                            ("before_discount", "سهم از مبلغ قبل از تخفیف"),
                            ("salon_absorbs", "تخفیف از سهم سالن کسر شود"),
                            ("platform_funded", "تأمین توسط پلتفرم"),
                        ],
                        default="after_discount",
                        max_length=32,
                        verbose_name="اثر روی سهم آرایشگر",
                    ),
                ),
                (
                    "eligible_payment_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="روش\u200cهای پرداخت مجاز",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان آرشیو"
                    ),
                ),
                (
                    "terms_text",
                    models.TextField(
                        blank=True, default="", verbose_name="قوانین قابل نمایش"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="آرشیوشده"),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کد های تخفیف",
            },
        ),
        migrations.CreateModel(
            name="DiscountBasket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_title",
                    models.CharField(max_length=100, verbose_name="عنوان تخفیف"),
                ),
                ("start_date", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateTimeField(verbose_name="تاریخ پایان")),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="اگر صفر باشد، سقف مبلغی برای این سبد تخفیف در نظر گرفته نمی\u200cشود.",
                        verbose_name="سقف مبلغ تخفیف (تومان)",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="آرشیوشده"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "درصدی"),
                            ("fixed_amount", "مبلغ ثابت"),
                        ],
                        default="percentage",
                        max_length=32,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "discount_value",
                    models.PositiveIntegerField(default=0, verbose_name="مقدار تخفیف"),
                ),
                (
                    "min_order_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حداقل مبلغ رزرو"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private_code", "کد خصوصی"),
                            ("public_code", "کد عمومی"),
                            ("search_badge", "نمایش در کارت و جستجو"),
                            ("checkout_only", "فقط در تسویه"),
                        ],
                        default="search_badge",
                        max_length=32,
                        verbose_name="نوع نمایش",
                    ),
                ),
                (
                    "funded_by",
                    models.CharField(
                        choices=[
                            ("salon", "سالن"),
                            ("platform", "Loomera"),
                            ("shared", "مشترک"),
                        ],
                        default="salon",
                        max_length=32,
                        verbose_name="تأمین\u200cکننده هزینه",
                    ),
                ),
                (
                    "salon_funding_percent",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="درصد سهم سالن از هزینه تخفیف"
                    ),
                ),
                (
                    "platform_funding_percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="درصد سهم Loomera از هزینه تخفیف"
                    ),
                ),
                (
                    "stacking_policy",
                    models.CharField(
                        choices=[
                            ("not_stackable", "قابل ترکیب نیست"),
                            ("stack_with_service", "قابل ترکیب با تخفیف خدمت"),
                            ("stack_with_platform", "قابل ترکیب با کمپین پلتفرم"),
                            ("best_only", "فقط بهترین تخفیف"),
                        ],
                        default="stack_with_service",
                        max_length=32,
                        verbose_name="قانون ترکیب",
                    ),
                ),
                (
                    "staff_share_impact",
                    models.CharField(
                        choices=[
                            ("after_discount", "سهم از مبلغ بعد از تخفیف"),
                            ("before_discount", "سهم از مبلغ قبل از تخفیف"),
                            ("salon_absorbs", "تخفیف از سهم سالن کسر شود"),
                            ("platform_funded", "تأمین توسط پلتفرم"),
                        ],
                        default="after_discount",
                        max_length=32,
                        verbose_name="اثر روی سهم آرایشگر",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان آرشیو"
                    ),
                ),
                (
                    "terms_text",
                    models.TextField(
                        blank=True, default="", verbose_name="قوانین قابل نمایش"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
            ],
            options={
                "verbose_name": "سبد تخفیف ",
                "verbose_name_plural": "سبدهای تخفیف ",
            },
        ),
        migrations.CreateModel(
            name="DiscountBasketDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "جزییات سبد تخفیف ",
                "verbose_name_plural": "جزئیات سبد تخفیف",
            },
        ),
        migrations.CreateModel(
            name="DiscountCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="عنوان کمپین")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default="",
                        max_length=180,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("salon", "سالن"),
                            ("platform", "Loomera"),
                            ("partner", "همکار"),
                        ],
                        default="salon",
                        max_length=32,
                        verbose_name="مالک کمپین",
                    ),
                ),
                (
                    "funded_by",
                    models.CharField(
                        choices=[
                            ("salon", "سالن"),
                            ("platform", "Loomera"),
                            ("shared", "مشترک"),
                        ],
                        default="salon",
                        max_length=32,
                        verbose_name="تأمین\u200cکننده هزینه",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("active", "فعال"),
                            ("paused", "متوقف"),
                            ("archived", "آرشیو شده"),
                        ],
                        default="active",
                        max_length=32,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "internal_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت داخلی"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("coupon", "کد تخفیف"),
                            ("basket", "سبد تخفیف"),
                            ("mixed", "کمپین ترکیبی"),
                        ],
                        default="mixed",
                        max_length=20,
                        verbose_name="نوع کمپین",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ شروع"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پایان"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="آرشیوشده"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "کمپین تخفیف",
                "verbose_name_plural": "کمپین\u200cهای تخفیف",
                "ordering": ["-is_active", "-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DiscountRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("coupon", "Coupon"),
                            ("basket", "Basket"),
                            ("campaign", "Campaign"),
                            ("manual", "Manual"),
                        ],
                        default="coupon",
                        max_length=20,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "اعمال\u200cشده"),
                            ("reserved", "رزرو شده"),
                            ("cancelled", "لغو شده"),
                            ("refunded", "عودت شده"),
                        ],
                        default="applied",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="کد/شناسه تخفیف",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=180,
                        verbose_name="عنوان تخفیف",
                    ),
                ),
                (
                    "percent",
                    models.PositiveIntegerField(default=0, verbose_name="درصد"),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(default=0, verbose_name="درصد تخفیف"),
                ),
                ("amount", models.PositiveIntegerField(default=0, verbose_name="مبلغ")),
                (
                    "discount_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مبلغ تخفیف"),
                ),
                (
                    "max_discount_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="سقف مبلغ تخفیف"
                    ),
                ),
                (
                    "eligible_subtotal",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ مشمول تخفیف"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ استفاده"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "استفاده از تخفیف",
                "verbose_name_plural": "استفاده\u200cهای تخفیف",
                "ordering": ["-redeemed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DiscountSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("coupon", "Coupon"),
                            ("basket", "Basket"),
                            ("campaign", "Campaign"),
                            ("manual", "Manual"),
                        ],
                        default="coupon",
                        max_length=20,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="کد/شناسه تخفیف",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=180,
                        verbose_name="عنوان تخفیف",
                    ),
                ),
                (
                    "percent",
                    models.PositiveIntegerField(default=0, verbose_name="درصد"),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(default=0, verbose_name="درصد تخفیف"),
                ),
                ("amount", models.PositiveIntegerField(default=0, verbose_name="مبلغ")),
                (
                    "discount_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مبلغ تخفیف"),
                ),
                (
                    "max_discount_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="سقف مبلغ تخفیف"
                    ),
                ),
                (
                    "eligible_subtotal",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ مشمول تخفیف"
                    ),
                ),
                (
                    "order_total_before_discount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ سفارش قبل از تخفیف"
                    ),
                ),
                (
                    "order_total_after_discount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ سفارش بعد از تخفیف"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="جزئیات محاسبه"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "اسنپ\u200cشات تخفیف",
                "verbose_name_plural": "اسنپ\u200cشات\u200cهای تخفیف",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DiscountStackingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="قانون تجمیع تخفیف",
                        max_length=140,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "policy",
                    models.CharField(
                        choices=[
                            ("best_discount_only", "بهترین تخفیف فقط"),
                            ("stack_all", "تجمیع همه تخفیف\u200cها"),
                            ("coupon_then_basket", "اول کد تخفیف سپس سبد"),
                            ("basket_then_coupon", "اول سبد سپس کد تخفیف"),
                            ("campaign_priority", "اولویت با کمپین"),
                        ],
                        default="best_discount_only",
                        max_length=40,
                        verbose_name="سیاست تجمیع",
                    ),
                ),
                (
                    "stacking_mode",
                    models.CharField(
                        choices=[
                            ("best_discount_only", "بهترین تخفیف فقط"),
                            ("stack_all", "تجمیع همه تخفیف\u200cها"),
                            ("coupon_then_basket", "اول کد تخفیف سپس سبد"),
                            ("basket_then_coupon", "اول سبد سپس کد تخفیف"),
                            ("campaign_priority", "اولویت با کمپین"),
                        ],
                        default="best_discount_only",
                        help_text="برای سازگاری با سرویس\u200cهای جدید و قدیمی همزمان نگهداری می\u200cشود.",
                        max_length=40,
                        verbose_name="حالت تجمیع",
                    ),
                ),
                (
                    "allow_coupon_with_basket",
                    models.BooleanField(
                        default=False, verbose_name="اجازه ترکیب کد و سبد"
                    ),
                ),
                (
                    "allow_coupon_with_campaign",
                    models.BooleanField(
                        default=False, verbose_name="اجازه ترکیب کد و کمپین"
                    ),
                ),
                (
                    "allow_basket_with_campaign",
                    models.BooleanField(
                        default=False, verbose_name="اجازه ترکیب سبد و کمپین"
                    ),
                ),
                (
                    "max_discount_sources",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="حداکثر تعداد منابع تخفیف"
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="اولویت"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "قانون تجمیع تخفیف",
                "verbose_name_plural": "قوانین تجمیع تخفیف",
                "ordering": ["-is_active", "priority", "-updated_at"],
            },
        ),
    ]
