# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_initial"),
        ("discounts", "0001_initial"),
        ("orders", "0001_initial"),
        ("salons", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="discountbasket",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_baskets",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="discountbasketdetails",
            name="discount_basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_basket_details1",
                to="discounts.discountbasket",
                verbose_name="سبد تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="discountbasketdetails",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_basket_details2",
                to="services.services",
                verbose_name="خدمت",
            ),
        ),
        migrations.AddField(
            model_name="discountbasketdetails",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_basket_details3",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="discountcampaign",
            name="baskets",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                to="discounts.discountbasket",
                verbose_name="سبدهای تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="discountcampaign",
            name="coupons",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                to="discounts.coupon",
                verbose_name="کدهای تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="discountcampaign",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_discount_campaigns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجادکننده",
            ),
        ),
        migrations.AddField(
            model_name="discountcampaign",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_campaigns",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="discountbasket",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_basket_links",
                to="discounts.discountcampaign",
                verbose_name="کمپین",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_coupon_links",
                to="discounts.discountcampaign",
                verbose_name="کمپین",
            ),
        ),
        migrations.AddField(
            model_name="discountredemption",
            name="basket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redemptions",
                to="discounts.discountbasket",
                verbose_name="سبد تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="discountredemption",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redemptions",
                to="discounts.discountcampaign",
                verbose_name="کمپین",
            ),
        ),
        migrations.AddField(
            model_name="discountredemption",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redemptions",
                to="discounts.coupon",
                verbose_name="کد تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="discountredemption",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_redemptions",
                to="accounts.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="discountredemption",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_redemptions",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AddField(
            model_name="discountredemption",
            name="order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_redemptions",
                to="orders.orderdetail",
                verbose_name="آیتم سفارش",
            ),
        ),
        migrations.AddField(
            model_name="discountredemption",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_redemptions",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="discountsnapshot",
            name="basket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_snapshots",
                to="discounts.discountbasket",
                verbose_name="سبد تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="discountsnapshot",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_snapshots",
                to="discounts.discountcampaign",
                verbose_name="کمپین",
            ),
        ),
        migrations.AddField(
            model_name="discountsnapshot",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_snapshots",
                to="discounts.coupon",
                verbose_name="کد تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="discountsnapshot",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_snapshots",
                to="accounts.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="discountsnapshot",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_snapshots",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AddField(
            model_name="discountsnapshot",
            name="order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_snapshots",
                to="orders.orderdetail",
                verbose_name="آیتم سفارش",
            ),
        ),
        migrations.AddField(
            model_name="discountsnapshot",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_snapshots",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="discountredemption",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redemptions",
                to="discounts.discountsnapshot",
                verbose_name="اسنپ\u200cشات تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="discountstackingpolicy",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                help_text="اگر خالی باشد، قانون به عنوان پیش\u200cفرض عمومی قابل استفاده است.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_stacking_policies",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountbasketdetails",
            constraint=models.UniqueConstraint(
                fields=("discount_basket", "service", "stylist"),
                name="disc_basket_svc_sty_u",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountcampaign",
            constraint=models.UniqueConstraint(
                fields=("salon", "title"), name="disc_campaign_title_u"
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.UniqueConstraint(
                fields=("salon", "coupon_code"), name="unique_coupon_per_salon"
            ),
        ),
        migrations.AddIndex(
            model_name="discountsnapshot",
            index=models.Index(
                fields=["order", "source_type"], name="disc_snap_order_source_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountsnapshot",
            index=models.Index(
                fields=["coupon", "customer"], name="disc_snap_coupon_customer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountredemption",
            index=models.Index(
                fields=["coupon", "customer"], name="disc_red_coupon_customer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountredemption",
            index=models.Index(
                fields=["order", "source_type"], name="disc_red_order_source_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountredemption",
            index=models.Index(
                fields=["status", "redeemed_at"], name="disc_red_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountstackingpolicy",
            index=models.Index(
                fields=["salon", "is_active"], name="disc_stack_salon_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountstackingpolicy",
            index=models.Index(
                fields=["policy", "is_active"], name="disc_stack_policy_active_idx"
            ),
        ),
    ]
