# Generated by Django 5.1.4 on 2026-05-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="عنوان مقاله")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=240,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                ("summary", models.TextField(verbose_name="خلاصه مقاله")),
                ("content", models.TextField(verbose_name="متن مقاله")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/articles/covers/",
                        verbose_name="تصویر شاخص",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("educational", "آموزشی"),
                            ("guide", "راهنمای انتخاب خدمت"),
                            ("case_study", "تحلیل نمونه\u200cکار"),
                            ("qa", "پرسش و پاسخ"),
                            ("trend", "ترند و ایده"),
                            ("news", "خبر و اطلاع\u200cرسانی"),
                        ],
                        default="educational",
                        max_length=30,
                        verbose_name="نوع محتوا",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending_review", "در انتظار بررسی"),
                            ("needs_revision", "نیازمند اصلاح"),
                            ("approved", "تأیید شده"),
                            ("published", "منتشر شده"),
                            ("rejected", "رد شده"),
                            ("archived", "آرشیو شده"),
                            ("hidden_by_salon", "مخفی شده توسط سالن"),
                            ("reported", "گزارش شده"),
                            ("suspended", "تعلیق شده"),
                            ("removed_by_loomera", "حذف شده توسط لومرا"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "عمومی"),
                            ("unlisted", "غیرقابل فهرست"),
                            (
                                "salon_followers",
                                "فقط دنبال\u200cکنندگان/علاقه\u200cمندان سالن",
                            ),
                        ],
                        default="public",
                        max_length=24,
                        verbose_name="نمایش",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "is_editor_pick",
                    models.BooleanField(default=False, verbose_name="منتخب سردبیر"),
                ),
                (
                    "is_educational",
                    models.BooleanField(default=True, verbose_name="محتوای آموزشی"),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(default=True, verbose_name="اجازه ایندکس SEO"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=220,
                        verbose_name="توضیحات SEO",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Canonical URL"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/articles/og/",
                        verbose_name="تصویر Open Graph",
                    ),
                ),
                (
                    "reading_time_minutes",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="زمان مطالعه تقریبی"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد پسندیدن"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="دلیل رد شدن"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "professional_confirmed_responsibility",
                    models.BooleanField(
                        default=False, verbose_name="تأیید مسئولیت توسط آرایشگر"
                    ),
                ),
                (
                    "professional_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید آرایشگر"
                    ),
                ),
                (
                    "professional_terms_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="نسخه قوانین آرایشگر",
                    ),
                ),
                (
                    "manager_approved_responsibility",
                    models.BooleanField(
                        default=False, verbose_name="تأیید مسئولیت توسط مدیر سالن"
                    ),
                ),
                (
                    "manager_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید مدیر"
                    ),
                ),
                (
                    "manager_terms_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="نسخه قوانین مدیر",
                    ),
                ),
                (
                    "contains_identifiable_client",
                    models.BooleanField(
                        default=False, verbose_name="دارای هویت قابل تشخیص مشتری"
                    ),
                ),
                (
                    "client_consent_status",
                    models.CharField(
                        default="not_required",
                        max_length=64,
                        verbose_name="وضعیت رضایت مشتری",
                    ),
                ),
                (
                    "report_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد گزارش"),
                ),
                (
                    "moderation_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت بررسی محتوا"
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان حذف/تعلیق"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
                "db_table": "articles_article",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ذخیره"),
                ),
            ],
            options={
                "verbose_name": "ذخیره مقاله",
                "verbose_name_plural": "ذخیره\u200cهای مقاله",
                "db_table": "articles_bookmark",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=120, verbose_name="عنوان دسته\u200cبندی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="برای URL پایدار دسته\u200cبندی استفاده می\u200cشود.",
                        max_length=160,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/articles/categories/",
                        verbose_name="تصویر دسته\u200cبندی",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=220,
                        verbose_name="توضیحات SEO",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی مقاله",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای مقاله",
                "db_table": "articles_category",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ArticleFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=220, verbose_name="سؤال")),
                ("answer", models.TextField(verbose_name="پاسخ")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "پرسش پرتکرار مقاله",
                "verbose_name_plural": "پرسش\u200cهای پرتکرار مقاله",
                "db_table": "articles_faq",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/articles/gallery/", verbose_name="تصویر"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=180, verbose_name="کپشن"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="متن جایگزین تصویر",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
            ],
            options={
                "verbose_name": "تصویر گالری مقاله",
                "verbose_name_plural": "تصاویر گالری مقاله",
                "db_table": "articles_gallery_image",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="عنوان تگ")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=120,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=220,
                        verbose_name="توضیحات SEO",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تگ مقاله",
                "verbose_name_plural": "تگ\u200cهای مقاله",
                "db_table": "articles_tag",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ArticleView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="کلید نشست"
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="هش IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="مرورگر"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان بازدید"),
                ),
            ],
            options={
                "verbose_name": "بازدید مقاله",
                "verbose_name_plural": "بازدیدهای مقاله",
                "db_table": "articles_view",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentModerationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(verbose_name="شناسه محتوا"),
                ),
                (
                    "event_type",
                    models.CharField(max_length=64, verbose_name="نوع رویداد"),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="وضعیت قبلی"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="وضعیت جدید"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "رویداد بررسی محتوا",
                "verbose_name_plural": "رویدادهای بررسی محتوا",
                "db_table": "articles_content_moderation_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(verbose_name="شناسه محتوا"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inappropriate", "محتوای نامناسب"),
                            ("no_permission", "تصویر یا محتوا بدون اجازه"),
                            ("misleading", "گمراه\u200cکننده یا نادرست"),
                            ("personal_info", "نمایش اطلاعات شخصی"),
                            ("off_platform", "تبلیغ خارج از لومرا"),
                            ("copyright", "نقض مالکیت محتوا"),
                            ("other", "سایر"),
                        ],
                        max_length=64,
                        verbose_name="دلیل گزارش",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیح"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("reviewed", "بررسی شده"),
                            ("accepted", "پذیرفته شده"),
                            ("rejected", "رد شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True, default="", verbose_name="نتیجه بررسی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ گزارش"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "گزارش محتوا",
                "verbose_name_plural": "گزارش\u200cهای محتوا",
                "db_table": "articles_content_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalonStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=140, verbose_name="عنوان استوری"),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=220,
                        verbose_name="توضیح کوتاه",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/articles/stories/covers/",
                        verbose_name="کاور استوری",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending_review", "در انتظار بررسی"),
                            ("needs_revision", "نیازمند اصلاح"),
                            ("approved", "تأیید شده"),
                            ("published", "منتشر شده"),
                            ("rejected", "رد شده"),
                            ("expired", "منقضی شده"),
                            ("archived", "آرشیو شده"),
                            ("hidden_by_salon", "مخفی شده توسط سالن"),
                            ("reported", "گزارش شده"),
                            ("suspended", "تعلیق شده"),
                            ("removed_by_loomera", "حذف شده توسط لومرا"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "عمومی"),
                            ("favorites_only", "فقط مشتریان علاقه\u200cمند به سالن"),
                            ("salon_page_only", "فقط صفحه سالن"),
                        ],
                        default="favorites_only",
                        max_length=24,
                        verbose_name="نمایش",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="زمان انقضا"
                    ),
                ),
                (
                    "cta_type",
                    models.CharField(
                        choices=[
                            ("none", "بدون دکمه"),
                            ("salon", "مشاهده سالن"),
                            ("booking", "رزرو"),
                            ("article", "مطالعه مقاله"),
                            ("service", "مشاهده خدمت"),
                            ("custom", "لینک سفارشی"),
                        ],
                        default="salon",
                        max_length=20,
                        verbose_name="نوع CTA",
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="متن دکمه"
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="لینک سفارشی",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد کلیک CTA"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="دلیل رد شدن"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "professional_confirmed_responsibility",
                    models.BooleanField(
                        default=False, verbose_name="تأیید مسئولیت توسط آرایشگر"
                    ),
                ),
                (
                    "professional_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید آرایشگر"
                    ),
                ),
                (
                    "professional_terms_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="نسخه قوانین آرایشگر",
                    ),
                ),
                (
                    "manager_approved_responsibility",
                    models.BooleanField(
                        default=False, verbose_name="تأیید مسئولیت توسط مدیر سالن"
                    ),
                ),
                (
                    "manager_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید مدیر"
                    ),
                ),
                (
                    "manager_terms_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="نسخه قوانین مدیر",
                    ),
                ),
                (
                    "contains_identifiable_client",
                    models.BooleanField(
                        default=False, verbose_name="دارای هویت قابل تشخیص مشتری"
                    ),
                ),
                (
                    "client_consent_status",
                    models.CharField(
                        default="not_required",
                        max_length=64,
                        verbose_name="وضعیت رضایت مشتری",
                    ),
                ),
                (
                    "report_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد گزارش"),
                ),
                (
                    "moderation_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت بررسی محتوا"
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان حذف/تعلیق"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "استوری سالن",
                "verbose_name_plural": "استوری\u200cهای سالن",
                "db_table": "articles_salon_story",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalonStoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "تصویر"), ("video", "ویدیو")],
                        default="image",
                        max_length=12,
                        verbose_name="نوع رسانه",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/articles/stories/items/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/articles/stories/",
                        verbose_name="ویدیو",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=260, verbose_name="کپشن"
                    ),
                ),
                (
                    "button_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="متن دکمه اسلاید",
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="لینک دکمه اسلاید",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="مدت نمایش"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "آیتم استوری سالن",
                "verbose_name_plural": "آیتم\u200cهای استوری سالن",
                "db_table": "articles_salon_story_item",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SalonStoryView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بازدید"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تکمیل مشاهده"
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید استوری سالن",
                "verbose_name_plural": "بازدیدهای استوری سالن",
                "db_table": "articles_salon_story_view",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffContentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("article", "مقاله"),
                            ("story", "استوری"),
                            ("portfolio", "نمونه\u200cکار"),
                        ],
                        max_length=32,
                        verbose_name="نوع محتوا",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="عنوان"
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, default="", verbose_name="متن/توضیح"),
                ),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="staff_content/submissions/",
                        verbose_name="فایل محتوا",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending_review", "در انتظار بررسی"),
                            ("needs_revision", "نیازمند اصلاح"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("published", "منتشر شده"),
                            ("archived", "آرشیو شده"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه محتوای منتشرشده"
                    ),
                ),
                (
                    "professional_confirmed_responsibility",
                    models.BooleanField(
                        default=False, verbose_name="تأیید مسئولیت توسط آرایشگر"
                    ),
                ),
                (
                    "professional_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید آرایشگر"
                    ),
                ),
                (
                    "manager_approved_responsibility",
                    models.BooleanField(
                        default=False, verbose_name="تأیید مسئولیت توسط مدیر سالن"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت بررسی"
                    ),
                ),
                (
                    "contains_identifiable_client",
                    models.BooleanField(
                        default=False, verbose_name="دارای هویت قابل تشخیص مشتری"
                    ),
                ),
                (
                    "client_consent_status",
                    models.CharField(
                        default="not_required",
                        max_length=64,
                        verbose_name="وضعیت رضایت مشتری",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "محتوای پیشنهادی آرایشگر",
                "verbose_name_plural": "محتواهای پیشنهادی آرایشگران",
                "db_table": "articles_staff_content_submission",
                "ordering": ["-created_at"],
            },
        ),
    ]
