# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_initial"),
        ("articles", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("salons", "0002_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="salons.salon",
                verbose_name="سالن مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="author_stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="accounts.stylist",
                verbose_name="متخصص نویسنده",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="author_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده کاربری",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="manager_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_approved_articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تأیید مسئولیت توسط",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="related_service_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_articles",
                to="services.groupservices",
                verbose_name="گروه\u200cهای خدمات مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="related_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_articles",
                to="services.services",
                verbose_name="خدمات مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حذف\u200cشده توسط",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="بررسی\u200cشده توسط",
            ),
        ),
        migrations.AddField(
            model_name="articlebookmark",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="articles.article",
                verbose_name="مقاله",
            ),
        ),
        migrations.AddField(
            model_name="articlebookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_bookmarks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="articlecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="articles.articlecategory",
                verbose_name="دسته والد",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="articles.articlecategory",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AddField(
            model_name="articlefaq",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="articles.article",
                verbose_name="مقاله",
            ),
        ),
        migrations.AddField(
            model_name="articlegalleryimage",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="articles.article",
                verbose_name="مقاله",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="articles.articletag",
                verbose_name="تگ\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="articleview",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="articles.article",
                verbose_name="مقاله",
            ),
        ),
        migrations.AddField(
            model_name="articleview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="contentmoderationevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_moderation_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر عامل",
            ),
        ),
        migrations.AddField(
            model_name="contentmoderationevent",
            name="target_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_moderation_events",
                to="contenttypes.contenttype",
                verbose_name="نوع محتوا",
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="گزارش\u200cدهنده",
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_content_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="بررسی\u200cشده توسط",
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="target_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_reports",
                to="contenttypes.contenttype",
                verbose_name="نوع محتوا",
            ),
        ),
        migrations.AddField(
            model_name="salonstory",
            name="manager_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_approved_stories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تأیید مسئولیت توسط",
            ),
        ),
        migrations.AddField(
            model_name="salonstory",
            name="related_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="articles.article",
                verbose_name="مقاله مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="salonstory",
            name="related_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="services.services",
                verbose_name="خدمت مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="salonstory",
            name="related_service_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="services.groupservices",
                verbose_name="گروه خدمت مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="salonstory",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_stories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حذف\u200cشده توسط",
            ),
        ),
        migrations.AddField(
            model_name="salonstory",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_stories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="بررسی\u200cشده توسط",
            ),
        ),
        migrations.AddField(
            model_name="salonstory",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="salonstory",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="accounts.stylist",
                verbose_name="متخصص مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="salonstoryitem",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="articles.salonstory",
                verbose_name="استوری",
            ),
        ),
        migrations.AddField(
            model_name="salonstoryview",
            name="last_item_seen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_seen_views",
                to="articles.salonstoryitem",
                verbose_name="آخرین آیتم دیده\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="salonstoryview",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="articles.salonstory",
                verbose_name="استوری",
            ),
        ),
        migrations.AddField(
            model_name="salonstoryview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="staffcontentsubmission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_staff_content_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="بررسی\u200cشده توسط",
            ),
        ),
        migrations.AddField(
            model_name="staffcontentsubmission",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_content_submissions",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="staffcontentsubmission",
            name="stylist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_submissions",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="staffcontentsubmission",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_content_submission_targets",
                to="contenttypes.contenttype",
                verbose_name="نوع محتوای منتشرشده",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articlebookmark",
            unique_together={("article", "user")},
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "published_at"], name="articles_ar_status_7759bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_featured", "status"], name="articles_ar_is_feat_cc188d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["content_type", "status"], name="articles_ar_content_b5100d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentmoderationevent",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="contmode_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentmoderationevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="contmode_event_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["status", "created_at"], name="contrept_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="contrept_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salonstory",
            index=models.Index(
                fields=["status", "published_at", "expires_at"],
                name="articles_sa_status_f1bdaf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salonstory",
            index=models.Index(
                fields=["salon", "status"], name="articles_sa_salon_i_f580ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salonstory",
            index=models.Index(
                fields=["visibility", "status"], name="articles_sa_visibil_4630f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salonstoryview",
            unique_together={("user", "story")},
        ),
        migrations.AddIndex(
            model_name="staffcontentsubmission",
            index=models.Index(
                fields=["salon", "status"], name="staffcont_salon_stat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffcontentsubmission",
            index=models.Index(
                fields=["stylist", "status"], name="staffcont_sty_stat_idx"
            ),
        ),
    ]
