# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyContentMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="شناسه محتوا"),
                ),
                (
                    "content_kind",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="گونه محتوا"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("views", models.PositiveIntegerField(default=0)),
                ("cta_clicks", models.PositiveIntegerField(default=0)),
                ("booking_starts", models.PositiveIntegerField(default=0)),
                ("booking_completed", models.PositiveIntegerField(default=0)),
                ("reports_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "شاخص روزانه محتوا",
                "verbose_name_plural": "شاخص\u200cهای روزانه محتوا",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyPlatformMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="تاریخ")),
                (
                    "users_total",
                    models.PositiveIntegerField(default=0, verbose_name="کل کاربران"),
                ),
                (
                    "customers_total",
                    models.PositiveIntegerField(default=0, verbose_name="کل مشتریان"),
                ),
                (
                    "salons_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کل سالن\u200cها"
                    ),
                ),
                (
                    "stylists_total",
                    models.PositiveIntegerField(default=0, verbose_name="کل آرایشگران"),
                ),
                (
                    "appointments_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کل نوبت\u200cها"
                    ),
                ),
                (
                    "completed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نوبت\u200cهای تکمیل\u200cشده"
                    ),
                ),
                (
                    "cancelled_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نوبت\u200cهای لغوشده"
                    ),
                ),
                (
                    "no_show_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدم حضور"),
                ),
                (
                    "disputed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="اختلاف\u200cها"
                    ),
                ),
                (
                    "gross_revenue",
                    models.PositiveBigIntegerField(default=0, verbose_name="فروش خام"),
                ),
                (
                    "customer_paid_total",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="مبلغ پرداختی/ثبت\u200cشده مشتری"
                    ),
                ),
                (
                    "platform_commission",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="کمیسیون پلتفرم"
                    ),
                ),
                (
                    "salon_net_profit",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="سود خالص سالن\u200cها"
                    ),
                ),
                (
                    "staff_net_profit",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="سود خالص آرایشگران"
                    ),
                ),
                (
                    "material_cost_total",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="هزینه مواد"
                    ),
                ),
                (
                    "content_reports_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="گزارش\u200cهای محتوا"
                    ),
                ),
                (
                    "support_open_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تیکت\u200cهای باز"
                    ),
                ),
                (
                    "disputes_open_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="اختلاف\u200cهای باز"
                    ),
                ),
                (
                    "notifications_failed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="اعلان\u200cهای ناموفق"
                    ),
                ),
                (
                    "searches_count",
                    models.PositiveIntegerField(default=0, verbose_name="جستجوها"),
                ),
                (
                    "no_result_searches_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="جستجوهای بدون نتیجه"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "شاخص روزانه پلتفرم",
                "verbose_name_plural": "شاخص\u200cهای روزانه پلتفرم",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailySalonMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("appointments_count", models.PositiveIntegerField(default=0)),
                ("completed_count", models.PositiveIntegerField(default=0)),
                ("cancelled_count", models.PositiveIntegerField(default=0)),
                ("no_show_count", models.PositiveIntegerField(default=0)),
                ("late_count", models.PositiveIntegerField(default=0)),
                ("overrun_count", models.PositiveIntegerField(default=0)),
                ("unique_customers", models.PositiveIntegerField(default=0)),
                ("new_customers", models.PositiveIntegerField(default=0)),
                ("repeat_customers", models.PositiveIntegerField(default=0)),
                ("gross_revenue", models.PositiveBigIntegerField(default=0)),
                ("customer_paid_total", models.PositiveBigIntegerField(default=0)),
                ("platform_commission", models.PositiveBigIntegerField(default=0)),
                ("salon_net_profit", models.PositiveBigIntegerField(default=0)),
                ("staff_payout_total", models.PositiveBigIntegerField(default=0)),
                ("material_cost_total", models.PositiveBigIntegerField(default=0)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "شاخص روزانه سالن",
                "verbose_name_plural": "شاخص\u200cهای روزانه سالن",
                "ordering": ["-date", "salon_id"],
            },
        ),
        migrations.CreateModel(
            name="DailySearchMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "normalized_query",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("query", models.CharField(blank=True, default="", max_length=255)),
                (
                    "filters_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("searches_count", models.PositiveIntegerField(default=0)),
                ("results_total", models.PositiveIntegerField(default=0)),
                ("no_result_count", models.PositiveIntegerField(default=0)),
                ("clicks_count", models.PositiveIntegerField(default=0)),
                ("booking_starts", models.PositiveIntegerField(default=0)),
                ("booking_completed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "شاخص روزانه جستجو",
                "verbose_name_plural": "شاخص\u200cهای روزانه جستجو",
                "ordering": ["-date", "normalized_query"],
            },
        ),
        migrations.CreateModel(
            name="DailyStaffMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("appointments_count", models.PositiveIntegerField(default=0)),
                ("completed_count", models.PositiveIntegerField(default=0)),
                ("late_count", models.PositiveIntegerField(default=0)),
                ("overrun_count", models.PositiveIntegerField(default=0)),
                ("no_show_count", models.PositiveIntegerField(default=0)),
                ("gross_share", models.PositiveBigIntegerField(default=0)),
                ("net_profit", models.BigIntegerField(default=0)),
                ("material_deduction", models.PositiveBigIntegerField(default=0)),
                ("payable_amount", models.BigIntegerField(default=0)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "شاخص روزانه آرایشگر",
                "verbose_name_plural": "شاخص\u200cهای روزانه آرایشگران",
                "ordering": ["-date", "stylist_id"],
            },
        ),
        migrations.CreateModel(
            name="ReportExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("platform_daily", "شاخص\u200cهای روزانه پلتفرم"),
                            ("salon_daily", "شاخص\u200cهای روزانه سالن"),
                            ("staff_daily", "شاخص\u200cهای روزانه آرایشگر"),
                            ("content_daily", "شاخص\u200cهای روزانه محتوا"),
                            ("search_daily", "شاخص\u200cهای روزانه جستجو"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("processing", "در حال پردازش"),
                            ("completed", "تکمیل شده"),
                            ("failed", "ناموفق"),
                            ("expired", "منقضی شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="report_exports/"
                    ),
                ),
                ("rows_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "درخواست خروجی گزارش",
                "verbose_name_plural": "درخواست\u200cهای خروجی گزارش",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("appointment", "نوبت"),
                            ("finance", "مالی"),
                            ("content", "محتوا"),
                            ("search", "جستجو"),
                            ("notification", "اعلان"),
                            ("support", "پشتیبانی"),
                            ("security", "امنیت"),
                            ("system", "سیستمی"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="دسته",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=96, verbose_name="نوع رویداد"
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="زمان وقوع",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="شناسه آبجکت هدف"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="کلید نشست"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="منبع"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد Analytics",
                "verbose_name_plural": "رویدادهای Analytics",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
