# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to="orders.orderdetail",
                verbose_name="آیتم رزرو",
            ),
        ),
    ]
