# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_initial"),
        ("analytics", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("salons", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to="contenttypes.contenttype",
                verbose_name="نوع آبجکت هدف",
            ),
        ),
        migrations.AddField(
            model_name="dailycontentmetric",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="نوع محتوا",
            ),
        ),
        migrations.AddField(
            model_name="dailycontentmetric",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_daily_metrics",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="dailysalonmetric",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_metrics",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddIndex(
            model_name="dailysearchmetric",
            index=models.Index(fields=["date"], name="dsearch_date_idx"),
        ),
        migrations.AddIndex(
            model_name="dailysearchmetric",
            index=models.Index(fields=["normalized_query"], name="dsearch_q_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailysearchmetric",
            constraint=models.UniqueConstraint(
                fields=("date", "normalized_query", "filters_hash"),
                name="uniq_d_search_metric",
            ),
        ),
        migrations.AddField(
            model_name="dailystaffmetric",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_daily_metrics",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="dailystaffmetric",
            name="stylist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_metrics",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="reportexportjob",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_export_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["category", "occurred_at"], name="an_evt_cat_dt"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "occurred_at"], name="an_evt_type_dt"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["salon", "occurred_at"], name="an_evt_salon_dt"),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["stylist", "occurred_at"], name="an_evt_staff_dt"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["order_detail"], name="an_evt_od_idx"),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="an_evt_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailycontentmetric",
            index=models.Index(fields=["date"], name="dcontent_date_idx"),
        ),
        migrations.AddIndex(
            model_name="dailycontentmetric",
            index=models.Index(
                fields=["content_type", "object_id"], name="dcontent_obj_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailycontentmetric",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "date"),
                name="uniq_d_content_metric",
            ),
        ),
        migrations.AddIndex(
            model_name="dailysalonmetric",
            index=models.Index(fields=["date"], name="dsalon_date_idx"),
        ),
        migrations.AddIndex(
            model_name="dailysalonmetric",
            index=models.Index(fields=["salon", "date"], name="dsalon_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailysalonmetric",
            constraint=models.UniqueConstraint(
                fields=("salon", "date"), name="uniq_d_salon_metric"
            ),
        ),
        migrations.AddIndex(
            model_name="dailystaffmetric",
            index=models.Index(fields=["date"], name="dstaff_date_idx"),
        ),
        migrations.AddIndex(
            model_name="dailystaffmetric",
            index=models.Index(fields=["stylist", "date"], name="dstaff_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailystaffmetric",
            constraint=models.UniqueConstraint(
                fields=("stylist", "salon", "date"), name="uniq_d_staff_metric"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexportjob",
            index=models.Index(
                fields=["status", "created_at"], name="rexport_status_dt"
            ),
        ),
    ]
