# Generated by Django 5.1.4 on 2026-07-17 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reportexportjob",
            index=models.Index(
                condition=models.Q(("status", "processing")),
                fields=["started_at"],
                name="rexport_proc_start",
            ),
        ),
        migrations.AddIndex(
            model_name="reportexportjob",
            index=models.Index(
                condition=models.Q(("status", "completed")),
                fields=["expires_at"],
                name="rexport_done_exp",
            ),
        ),
        migrations.AddIndex(
            model_name="reportexportjob",
            index=models.Index(
                condition=models.Q(("status", "completed")),
                fields=["completed_at"],
                name="rexport_done_comp",
            ),
        ),
        migrations.AddIndex(
            model_name="reportexportjob",
            index=models.Index(
                condition=models.Q(("status", "failed")),
                fields=["completed_at"],
                name="rexport_fail_comp",
            ),
        ),
        migrations.AddIndex(
            model_name="reportexportjob",
            index=models.Index(
                condition=models.Q(("status", "expired")),
                fields=["updated_at"],
                name="rexport_exp_upd",
            ),
        ),
    ]
