# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "ایجاد شد"),
                            ("status_changed", "تغییر وضعیت"),
                            ("evidence_requested", "درخواست مدرک"),
                            ("evidence_added", "مدرک ثبت شد"),
                            ("resolved", "حل شد"),
                            ("financial_adjustment_linked", "اصلاح مالی متصل شد"),
                            ("note", "یادداشت"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="نوع رویداد",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="وضعیت قبلی"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="وضعیت جدید"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد اختلاف",
                "verbose_name_plural": "رویدادهای اختلاف",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MediaProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه هدف"
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to="processing/source/%Y/%m/", verbose_name="فایل اصلی"
                    ),
                ),
                (
                    "processed_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="processing/processed/%Y/%m/",
                        verbose_name="فایل پردازش\u200cشده",
                    ),
                ),
                (
                    "thumbnail_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="processing/thumbs/%Y/%m/",
                        verbose_name="تصویر بندانگشتی",
                    ),
                ),
                (
                    "file_kind",
                    models.CharField(
                        choices=[
                            ("public_image", "تصویر عمومی"),
                            ("private_document", "سند خصوصی"),
                            ("support_attachment", "پیوست پشتیبانی"),
                            ("verification_document", "مدرک احراز"),
                            ("other", "سایر"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=48,
                        verbose_name="نوع فایل",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="MIME"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="حجم"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("processing", "در حال پردازش"),
                            ("completed", "کامل شده"),
                            ("failed", "ناموفق"),
                            ("skipped", "رد شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد تلاش"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="خطا"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پردازش"
                    ),
                ),
            ],
            options={
                "verbose_name": "job پردازش فایل",
                "verbose_name_plural": "jobهای پردازش فایل",
                "db_table": "M_MediaProcessingJobs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OperationalJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="نام job"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "شروع شده"),
                            ("success", "موفق"),
                            ("failed", "ناموفق"),
                            ("skipped", "رد شده"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="شروع",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مدت اجرا به میلی\u200cثانیه"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="خلاصه"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="خطا"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
            ],
            options={
                "verbose_name": "اجرای job عملیاتی",
                "verbose_name_plural": "اجرای jobهای عملیاتی",
                "db_table": "M_OperationalJobRuns",
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(max_length=120, unique=True, verbose_name="کلید"),
                ),
                (
                    "value",
                    models.JSONField(blank=True, default=dict, verbose_name="مقدار"),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("string", "String"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=16,
                        verbose_name="نوع مقدار",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
                (
                    "is_sensitive",
                    models.BooleanField(default=False, verbose_name="حساس است"),
                ),
                (
                    "is_runtime_editable",
                    models.BooleanField(
                        default=False,
                        help_text="تنظیمات پرریسک باید از env/config کنترل شوند، نه صرفاً دیتابیس.",
                        verbose_name="قابل تغییر از پنل عملیاتی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تنظیم پلتفرم",
                "verbose_name_plural": "تنظیمات پلتفرم",
                "db_table": "M_PlatformSettings",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="نوع رویداد"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "اطلاع\u200cرسانی"),
                            ("warning", "هشدار"),
                            ("critical", "بحرانی"),
                        ],
                        default="info",
                        max_length=16,
                        verbose_name="شدت",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه هدف"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ امنیتی",
                "verbose_name_plural": "لاگ\u200cهای امنیتی",
                "db_table": "M_SecurityAuditLogs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SupportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="support_attachments/", verbose_name="فایل"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="نوع فایل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
            ],
            options={
                "verbose_name": "پیوست تیکت",
                "verbose_name_plural": "پیوست\u200cهای تیکت",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SupportEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "ایجاد شد"),
                            ("message_added", "پیام ثبت شد"),
                            ("status_changed", "وضعیت تغییر کرد"),
                            ("assigned", "ارجاع شد"),
                            ("priority_changed", "اولویت تغییر کرد"),
                            ("closed", "بسته شد"),
                            ("reopened", "بازگشایی شد"),
                            ("dispute_linked", "پرونده اختلاف متصل شد"),
                            ("note", "یادداشت"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="نوع رویداد",
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="مقدار قبلی"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="مقدار جدید"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ثبت"
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد پشتیبانی",
                "verbose_name_plural": "رویدادهای پشتیبانی",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام کامل"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="شهر"),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره موبایل"
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("account_existing", "پشتیبانی حساب موجود"),
                            ("account_join", "درخواست پیوستن کسب\u200cوکار"),
                            ("appointment", "پشتیبانی نوبت"),
                            ("other", "سایر موارد"),
                        ],
                        max_length=32,
                        verbose_name="نوع درخواست",
                    ),
                ),
                (
                    "support_reason",
                    models.CharField(blank=True, max_length=64, verbose_name="موضوع"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="شرح درخواست"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="support_tickets/",
                        verbose_name="پیوست",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("account", "حساب کاربری"),
                            ("booking", "رزرو و نوبت"),
                            ("cancellation", "لغو نوبت"),
                            ("no_show", "عدم حضور"),
                            ("payment", "پرداخت"),
                            ("finance", "مالی"),
                            ("staff_payout", "پرداخت سهم آرایشگر"),
                            ("salon_verification", "احراز سالن"),
                            ("content_report", "گزارش محتوا"),
                            ("review_report", "گزارش نظر"),
                            ("technical_bug", "خطای فنی"),
                            ("refund", "برگشت وجه"),
                            ("compensation", "جبران مشتری"),
                            ("membership_access", "عضویت و دسترسی"),
                            ("other", "سایر"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=64,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="زیرگروه"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("open", "باز"),
                            ("in_progress", "در حال بررسی"),
                            ("waiting_for_support", "در انتظار پشتیبانی"),
                            ("waiting_for_user", "در انتظار کاربر"),
                            ("waiting_for_salon", "در انتظار سالن"),
                            ("waiting_for_stylist", "در انتظار آرایشگر"),
                            ("waiting_for_finance", "در انتظار مالی"),
                            ("waiting_for_admin_review", "در انتظار بررسی ادمین"),
                            ("resolved", "حل شده"),
                            ("closed", "بسته شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=40,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "عادی"),
                            ("high", "مهم"),
                            ("urgent", "فوری"),
                            ("critical", "بحرانی"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=20,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "requester_role",
                    models.CharField(
                        choices=[
                            ("customer", "مشتری"),
                            ("salon_manager", "مدیر سالن"),
                            ("stylist", "آرایشگر"),
                            ("guest", "مهمان"),
                            ("admin", "ادمین"),
                        ],
                        default="customer",
                        max_length=32,
                        verbose_name="نقش درخواست\u200cکننده",
                    ),
                ),
                (
                    "assigned_team",
                    models.CharField(
                        choices=[
                            ("support", "پشتیبانی"),
                            ("finance", "مالی"),
                            ("content_moderation", "کنترل محتوا"),
                            ("verification", "احراز"),
                            ("technical", "فنی"),
                        ],
                        db_index=True,
                        default="support",
                        max_length=64,
                        verbose_name="تیم مسئول",
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه آبجکت مرتبط"
                    ),
                ),
                (
                    "admin_reply",
                    models.TextField(blank=True, verbose_name="آخرین پاسخ ادمین"),
                ),
                (
                    "sla_due_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="مهلت پاسخ/رسیدگی",
                    ),
                ),
                (
                    "first_response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="اولین پاسخ"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="زمان حل"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بسته\u200cشدن"
                    ),
                ),
                (
                    "last_response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین پاسخ"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تیکت پشتیبانی",
                "verbose_name_plural": "تیکت\u200cهای پشتیبانی",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("customer", "مشتری"),
                            ("salon_manager", "مدیر سالن"),
                            ("stylist", "آرایشگر"),
                            ("guest", "مهمان"),
                            ("admin", "ادمین"),
                            ("support_admin", "ادمین پشتیبانی"),
                            ("finance_admin", "ادمین مالی"),
                            ("content_moderator", "ناظر محتوا"),
                            ("system", "سیستم"),
                        ],
                        default="customer",
                        max_length=40,
                        verbose_name="نقش فرستنده",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("public", "عمومی"),
                            ("internal", "یادداشت داخلی"),
                            ("system", "سیستمی"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=16,
                        verbose_name="نوع پیام",
                    ),
                ),
                ("body", models.TextField(verbose_name="متن پیام")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ثبت"
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام تیکت",
                "verbose_name_plural": "پیام\u200cهای تیکت",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="SuspensionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(verbose_name="شناسه هدف"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("expired", "منقضی"),
                            ("revoked", "لغوشده"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="دلیل")),
                (
                    "internal_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت داخلی"
                    ),
                ),
                (
                    "user_facing_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="دلیل قابل نمایش به کاربر"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="شروع"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان/انقضا"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان لغو"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "رکورد تعلیق",
                "verbose_name_plural": "رکوردهای تعلیق",
                "db_table": "M_SuspensionRecords",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="عملیات"
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه هدف"
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="مقدار قبلی"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="مقدار جدید"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="دلیل")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده تکمیلی"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اقدام\u200cکننده",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="نوع هدف",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ ادمین",
                "verbose_name_plural": "لاگ\u200cهای ادمین",
                "db_table": "M_AdminAuditLogs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AdminRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("support_admin", "Support Admin"),
                            ("finance_admin", "Finance Admin"),
                            ("content_moderator", "Content Moderator"),
                            ("verification_admin", "Verification Admin"),
                            ("read_only_admin", "Read-only Admin"),
                        ],
                        db_index=True,
                        max_length=48,
                        verbose_name="نقش داخلی",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="فعال"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_platform_admin_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعطاکننده نقش",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_admin_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر ادمین",
                    ),
                ),
            ],
            options={
                "verbose_name": "نقش داخلی ادمین",
                "verbose_name_plural": "نقش\u200cهای داخلی ادمین",
                "db_table": "M_AdminRoleAssignments",
                "ordering": ["user_id", "role"],
            },
        ),
        migrations.CreateModel(
            name="DisputeCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispute_type",
                    models.CharField(
                        choices=[
                            ("no_show", "اعتراض عدم حضور"),
                            ("financial", "اختلاف مالی"),
                            ("cancellation", "لغو و جبران"),
                            ("content_rights", "حقوق محتوا/تصویر"),
                            ("review", "اختلاف نظر/امتیاز"),
                            ("staff_payout", "اختلاف پرداخت سهم آرایشگر"),
                            ("general", "سایر"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="نوع اختلاف",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("opened", "باز شده"),
                            ("under_review", "در حال بررسی"),
                            ("waiting_for_evidence", "در انتظار مدرک"),
                            ("resolved_for_customer", "حل به نفع مشتری"),
                            ("resolved_for_salon", "حل به نفع سالن"),
                            ("resolved_partially", "حل جزئی"),
                            ("rejected", "رد شده"),
                            ("closed", "بسته شده"),
                        ],
                        db_index=True,
                        default="opened",
                        max_length=40,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "عادی"),
                            ("high", "مهم"),
                            ("urgent", "فوری"),
                            ("critical", "بحرانی"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=20,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه هدف مرتبط"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="شرح اختلاف"),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="نتیجه"
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت نتیجه"
                    ),
                ),
                (
                    "refund_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="مبلغ برگشت وجه"
                    ),
                ),
                (
                    "compensation_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="مبلغ جبران"
                    ),
                ),
                (
                    "financial_impact_amount",
                    models.BigIntegerField(default=0, verbose_name="اثر مالی"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="زمان حل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispute_cases",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرونده اختلاف",
                "verbose_name_plural": "پرونده\u200cهای اختلاف",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
