# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0001_initial"),
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="disputecase",
            name="financial_adjustment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_cases",
                to="payments.financialadjustment",
                verbose_name="اصلاح مالی",
            ),
        ),
        migrations.AddField(
            model_name="disputecase",
            name="financial_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_cases",
                to="payments.orderdetailfinancialsnapshot",
                verbose_name="سند مالی",
            ),
        ),
        migrations.AddField(
            model_name="disputecase",
            name="opened_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opened_disputes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="disputecase",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_cases",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AddField(
            model_name="disputecase",
            name="order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_cases",
                to="orders.orderdetail",
                verbose_name="آیتم نوبت",
            ),
        ),
        migrations.AddField(
            model_name="disputecase",
            name="related_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_related_cases",
                to="contenttypes.contenttype",
                verbose_name="نوع هدف مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="disputecase",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_disputes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حل\u200cکننده",
            ),
        ),
    ]
