# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0002_initial"),
        ("orders", "0002_initial"),
        ("salons", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="disputecase",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_cases",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="disputecase",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_cases",
                to="accounts.stylist",
                verbose_name="آرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="disputeevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="انجام\u200cدهنده",
            ),
        ),
        migrations.AddField(
            model_name="disputeevent",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="main.disputecase",
                verbose_name="پرونده اختلاف",
            ),
        ),
        migrations.AddField(
            model_name="mediaprocessingjob",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_media_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="mediaprocessingjob",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_processing_jobs",
                to="contenttypes.contenttype",
                verbose_name="نوع هدف",
            ),
        ),
        migrations.AddIndex(
            model_name="operationaljobrun",
            index=models.Index(
                fields=["job_name", "status"], name="jobrun_name_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operationaljobrun",
            index=models.Index(fields=["started_at"], name="jobrun_started_idx"),
        ),
        migrations.AddField(
            model_name="platformsetting",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_platform_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخرین ویرایشگر",
            ),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="نوع هدف",
            ),
        ),
        migrations.AddField(
            model_name="supportattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_attachments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="بارگذاری\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="supportevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="انجام\u200cدهنده",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_support_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسئول رسیدگی",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="last_response_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_support_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخرین پاسخ\u200cدهنده",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_tickets",
                to="orders.order",
                verbose_name="سفارش مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_tickets",
                to="orders.orderdetail",
                verbose_name="آیتم نوبت مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="related_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_related_tickets",
                to="contenttypes.contenttype",
                verbose_name="نوع آبجکت مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_tickets",
                to="salons.salon",
                verbose_name="سالن مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_tickets",
                to="accounts.stylist",
                verbose_name="آرایشگر مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="supportevent",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="main.supportticket",
                verbose_name="تیکت",
            ),
        ),
        migrations.AddField(
            model_name="supportattachment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="main.supportticket",
                verbose_name="تیکت",
            ),
        ),
        migrations.AddField(
            model_name="disputecase",
            name="support_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_cases",
                to="main.supportticket",
                verbose_name="تیکت پشتیبانی",
            ),
        ),
        migrations.AddField(
            model_name="supportticketmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="فرستنده",
            ),
        ),
        migrations.AddField(
            model_name="supportticketmessage",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="main.supportticket",
                verbose_name="تیکت",
            ),
        ),
        migrations.AddField(
            model_name="supportattachment",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="main.supportticketmessage",
                verbose_name="پیام",
            ),
        ),
        migrations.AddField(
            model_name="suspensionrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_suspensions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="suspensionrecord",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_suspensions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="لغوکننده",
            ),
        ),
        migrations.AddField(
            model_name="suspensionrecord",
            name="target_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suspension_records",
                to="contenttypes.contenttype",
                verbose_name="نوع هدف",
            ),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(
                fields=["action", "-created_at"], name="M_AdminAudi_action_aab295_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="M_AdminAudi_target__bddaf2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminroleassignment",
            index=models.Index(
                fields=["role", "is_active"], name="admrole_role_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="adminroleassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "role"), name="uniq_admin_role_user"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevent",
            index=models.Index(
                fields=["dispute", "created_at"], name="dispevt_case_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaprocessingjob",
            index=models.Index(
                fields=["status", "created_at"], name="mediajob_status_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaprocessingjob",
            index=models.Index(
                fields=["file_kind", "status"], name="mediajob_kind_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="M_SecurityA_event_t_28a321_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityauditlog",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="M_SecurityA_severit_312e08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["status", "priority"], name="supp_status_prio_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["category", "status"], name="supp_cat_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["assigned_team", "status"], name="supp_team_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["salon", "status"], name="supp_salon_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["order_detail", "status"], name="supp_orddet_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportevent",
            index=models.Index(
                fields=["ticket", "created_at"], name="suppevt_ticket_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputecase",
            index=models.Index(
                fields=["dispute_type", "status"], name="disp_type_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputecase",
            index=models.Index(
                fields=["salon", "status"], name="disp_salon_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputecase",
            index=models.Index(
                fields=["order_detail", "status"], name="disp_orddet_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticketmessage",
            index=models.Index(
                fields=["ticket", "created_at"], name="suppmsg_ticket_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suspensionrecord",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="susp_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="suspensionrecord",
            index=models.Index(
                fields=["status", "created_at"], name="susp_status_time_idx"
            ),
        ),
    ]
