# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("dashboard", "داشبورد"),
                            ("email", "ایمیل"),
                            ("sms", "پیامک"),
                            ("whatsapp", "واتس\u200cاپ"),
                            ("bale", "بله"),
                            ("telegram", "تلگرام"),
                            ("rubika", "روبیکا"),
                            ("system", "سیستم"),
                        ],
                        max_length=24,
                        verbose_name="کانال",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("queued", "در صف"),
                            ("sent", "ارسال شد"),
                            ("failed", "ناموفق"),
                            ("skipped", "ارسال نشد"),
                            ("pending_setup", "نیازمند تنظیمات"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="provider"
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد تلاش"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان برنامه\u200cریزی"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال"
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان خطا"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="آخرین خطا"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
            ],
            options={
                "verbose_name": "ارسال اعلان",
                "verbose_name_plural": "ارسال\u200cهای اعلان",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(verbose_name="شماره تلاش"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("queued", "در صف"),
                            ("sent", "ارسال شد"),
                            ("failed", "ناموفق"),
                            ("skipped", "ارسال نشد"),
                            ("pending_setup", "نیازمند تنظیمات"),
                        ],
                        max_length=24,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="provider"
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ provider"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "تلاش ارسال اعلان",
                "verbose_name_plural": "تلاش\u200cهای ارسال اعلان",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "مشتری"),
                            ("stylist", "آرایشگر"),
                            ("manager", "مدیر سالن"),
                            ("admin", "ادمین Loomera"),
                            ("system", "سیستم"),
                        ],
                        default="",
                        max_length=24,
                        verbose_name="نقش مخاطب",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("booking", "رزرو"),
                            ("payment", "پرداخت"),
                            ("finance", "مالی"),
                            ("staff", "آرایشگر و تیم"),
                            ("content", "محتوا"),
                            ("support", "پشتیبانی"),
                            ("verification", "احراز"),
                            ("system", "سیستمی"),
                            ("marketing", "پیشنهادها"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True, default="", max_length=96, verbose_name="نوع رویداد"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("dashboard", "داشبورد"),
                            ("email", "ایمیل"),
                            ("sms", "پیامک"),
                            ("whatsapp", "واتس\u200cاپ"),
                            ("bale", "بله"),
                            ("telegram", "تلگرام"),
                            ("rubika", "روبیکا"),
                            ("system", "سیستم"),
                        ],
                        max_length=24,
                        verbose_name="کانال",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
            ],
            options={
                "verbose_name": "تنظیم اعلان",
                "verbose_name_plural": "تنظیمات اعلان",
            },
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience_role",
                    models.CharField(
                        choices=[
                            ("customer", "مشتری"),
                            ("stylist", "آرایشگر"),
                            ("manager", "مدیر سالن"),
                            ("admin", "ادمین Loomera"),
                            ("system", "سیستم"),
                        ],
                        db_index=True,
                        default="customer",
                        max_length=24,
                        verbose_name="نقش مخاطب",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="خوانده شده"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان خواندن"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="آرشیو شده"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان آرشیو"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name": "گیرنده اعلان",
                "verbose_name_plural": "گیرندگان اعلان",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=96, verbose_name="نوع رویداد"
                    ),
                ),
                (
                    "audience_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "مشتری"),
                            ("stylist", "آرایشگر"),
                            ("manager", "مدیر سالن"),
                            ("admin", "ادمین Loomera"),
                            ("system", "سیستم"),
                        ],
                        db_index=True,
                        default="",
                        max_length=24,
                        verbose_name="نقش مخاطب",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("dashboard", "داشبورد"),
                            ("email", "ایمیل"),
                            ("sms", "پیامک"),
                            ("whatsapp", "واتس\u200cاپ"),
                            ("bale", "بله"),
                            ("telegram", "تلگرام"),
                            ("rubika", "روبیکا"),
                            ("system", "سیستم"),
                        ],
                        db_index=True,
                        default="dashboard",
                        max_length=24,
                        verbose_name="کانال",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("booking", "رزرو"),
                            ("payment", "پرداخت"),
                            ("finance", "مالی"),
                            ("staff", "آرایشگر و تیم"),
                            ("content", "محتوا"),
                            ("support", "پشتیبانی"),
                            ("verification", "احراز"),
                            ("system", "سیستمی"),
                            ("marketing", "پیشنهادها"),
                        ],
                        default="system",
                        max_length=32,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "کم"),
                            ("normal", "معمولی"),
                            ("high", "مهم"),
                            ("critical", "حیاتی"),
                        ],
                        default="normal",
                        max_length=16,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(max_length=180, verbose_name="قالب عنوان"),
                ),
                (
                    "body_template",
                    models.TextField(blank=True, default="", verbose_name="قالب متن"),
                ),
                (
                    "action_url_template",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="قالب لینک اقدام",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="fa-regular fa-bell",
                        max_length=80,
                        verbose_name="آیکون",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="فعال"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
            ],
            options={
                "verbose_name": "قالب اعلان",
                "verbose_name_plural": "قالب\u200cهای اعلان",
                "ordering": ["event_type", "audience_role", "channel"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=96, verbose_name="نوع رویداد"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("booking", "رزرو"),
                            ("payment", "پرداخت"),
                            ("finance", "مالی"),
                            ("staff", "آرایشگر و تیم"),
                            ("content", "محتوا"),
                            ("support", "پشتیبانی"),
                            ("verification", "احراز"),
                            ("system", "سیستمی"),
                            ("marketing", "پیشنهادها"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=32,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "کم"),
                            ("normal", "معمولی"),
                            ("high", "مهم"),
                            ("critical", "حیاتی"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=16,
                        verbose_name="اولویت",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="عنوان")),
                ("body", models.TextField(blank=True, default="", verbose_name="متن")),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="لینک اقدام",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="fa-regular fa-bell",
                        max_length=80,
                        verbose_name="آیکون",
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه آبجکت مرتبط"
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=180,
                        verbose_name="کلید جلوگیری از تکرار",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="نوع آبجکت مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان یکپارچه",
                "verbose_name_plural": "اعلان\u200cهای یکپارچه",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
