# Generated by Django 5.1.4 on 2026-05-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("salons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="salons.salon",
                verbose_name="سالن",
            ),
        ),
        migrations.AddField(
            model_name="notificationdeliveryattempt",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="notifications.notificationdelivery",
                verbose_name="ارسال",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecipient",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="notifications.notification",
                verbose_name="اعلان",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecipient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_recipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="notifications.notificationrecipient",
                verbose_name="گیرنده",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["event_type", "channel"], name="notif_tmpl_evt_ch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["is_active", "event_type"], name="notif_tmpl_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.UniqueConstraint(
                fields=("event_type", "audience_role", "channel"),
                name="uniq_notif_template",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["event_type", "-created_at"], name="notif_evt_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["category", "-created_at"], name="notif_cat_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["salon", "-created_at"], name="notif_salon_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key", ""), _negated=True),
                fields=("dedupe_key",),
                name="uniq_notif_dedupe",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliveryattempt",
            index=models.Index(
                fields=["delivery", "-created_at"], name="notif_att_deliv_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("delivery", "attempt_number"), name="uniq_notif_deliv_att"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["user", "channel", "is_enabled"], name="notif_pref_user_ch_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "audience_role", "category", "event_type", "channel"),
                name="uniq_notif_pref",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["user", "is_read", "-created_at"], name="notif_rec_read_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["user", "audience_role", "-created_at"],
                name="notif_rec_role_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationrecipient",
            constraint=models.UniqueConstraint(
                fields=("notification", "user", "audience_role"),
                name="uniq_notif_recipient",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["channel", "status", "created_at"], name="notif_deliv_queue_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "created_at"], name="notif_deliv_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("recipient", "channel"), name="uniq_notif_delivery"
            ),
        ),
    ]
