# Generated by Django 5.1.4 on 2026-07-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("booking", "رزرو"),
                    ("payment", "پرداخت"),
                    ("finance", "مالی"),
                    ("staff", "متخصص و تیم"),
                    ("content", "محتوا"),
                    ("support", "پشتیبانی"),
                    ("verification", "احراز"),
                    ("system", "سیستمی"),
                    ("marketing", "پیشنهادها"),
                ],
                db_index=True,
                default="system",
                max_length=32,
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="audience_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer", "مشتری"),
                    ("stylist", "متخصص"),
                    ("manager", "مدیر سالن"),
                    ("admin", "ادمین Loomera"),
                    ("system", "سیستم"),
                ],
                default="",
                max_length=24,
                verbose_name="نقش مخاطب",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("booking", "رزرو"),
                    ("payment", "پرداخت"),
                    ("finance", "مالی"),
                    ("staff", "متخصص و تیم"),
                    ("content", "محتوا"),
                    ("support", "پشتیبانی"),
                    ("verification", "احراز"),
                    ("system", "سیستمی"),
                    ("marketing", "پیشنهادها"),
                ],
                default="",
                max_length=32,
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecipient",
            name="audience_role",
            field=models.CharField(
                choices=[
                    ("customer", "مشتری"),
                    ("stylist", "متخصص"),
                    ("manager", "مدیر سالن"),
                    ("admin", "ادمین Loomera"),
                    ("system", "سیستم"),
                ],
                db_index=True,
                default="customer",
                max_length=24,
                verbose_name="نقش مخاطب",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="audience_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer", "مشتری"),
                    ("stylist", "متخصص"),
                    ("manager", "مدیر سالن"),
                    ("admin", "ادمین Loomera"),
                    ("system", "سیستم"),
                ],
                db_index=True,
                default="",
                max_length=24,
                verbose_name="نقش مخاطب",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("booking", "رزرو"),
                    ("payment", "پرداخت"),
                    ("finance", "مالی"),
                    ("staff", "متخصص و تیم"),
                    ("content", "محتوا"),
                    ("support", "پشتیبانی"),
                    ("verification", "احراز"),
                    ("system", "سیستمی"),
                    ("marketing", "پیشنهادها"),
                ],
                default="system",
                max_length=32,
                verbose_name="دسته\u200cبندی",
            ),
        ),
    ]
